### ISSUE TITLE
Unmet dependencies problem: daemon

### ISSUE THREAD

**Issue by sanderfiers** [geerlingguy/ansible-role-jenkins#101]
jenkins : Depends: daemon but it is not installable

TASK [roles/geerlingguy.jenkins : Validate Jenkins is installed and register package name.] ***
fatal: [PAL-ansibleclient01]: FAILED! => {"cache_update_time": 0, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'jenkins'' failed: E: Unable to correct problems, you have held broken packages.\n", "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n jenkins : Depends: daemon but it is not installable\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " jenkins : Depends: daemon but it is not installable"]}

**Comment by arthurkhlghatyan** [comment]
Same problem here. Any updates on this?

**Comment by geerlingguy** [comment]
@sanderfiers @arthurkhlghatyan - Can you give more information about what OS/version you're running? Also, if you have any other things (like different PPAs) installed that could affect Jenkins' install?

**Comment by valerian** [comment]
I am experiencing the same issue with ansible 2.3.0.0 by running only the geerlingguy.jenkins role on freshly spawned vagrant vm, tried with "debian/jessie64" and "ubuntu/trusty64"

**Comment by gtrs** [comment]
I can confirm this problem on a plain Ubuntu 18.04 server installation.

Ubuntu server seems to enable only the `main` repository in a plain installation. The `jenkins` package relies on the package `daemon`, which is contained in the `universe` repository.

To solve this problem, the ansible role should make sure that the `universe` repository is enabled.
