### ISSUE TITLE
Install Jenkins plugins using password failed

### ISSUE THREAD

**Issue by ghost** [geerlingguy/ansible-role-jenkins#106]
TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ***********
failed: [ec2-52-213-150-14.eu-west-1.compute.amazonaws.com] (item=git-parameter) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://localhost:8080/", "install-plugin", "git-parameter", "--username", "admin", "--password", "admin"], "delta": "0:00:07.937499", "end": "2016-12-25 18:32:26.503943", "failed": true, "item": "git-parameter", "rc": 255, "start": "2016-12-25 18:32:18.566444", "stderr": "Dec 25, 2016 6:32:26 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run\nSEVERE: I/O error in channel Chunked connection to http://localhost:8080/cli\njava.io.IOException: Unexpected termination of the channel\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)\nCaused by: java.io.EOFException\n\tat java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2353)\n\tat java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2822)\n\tat java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)\n\tat java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)\n\tat hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)\n\tat hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)\n\nhudson.remoting.RequestAbortedException: java.io.IOException: Unexpected termination of the channel\n\tat hudson.remoting.Request.abort(Request.java:307)\n\tat hudson.remoting.Channel.terminate(Channel.java:888)\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:92)\n\tat ......remote call to Chunked connection to http://localhost:8080/cli(Native Method)\n\tat hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1537)\n\tat hudson.remoting.Request.call(Request.java:172)\n\tat hudson.remoting.Channel.call(Channel.java:821)\n\tat hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:256)\n\tat com.sun.proxy.$Proxy3.main(Unknown Source)\n\tat hudson.cli.CLI.execute(CLI.java:333)\n\tat hudson.cli.CLI._main(CLI.java:504)\n\tat hudson.cli.CLI.main(CLI.java:385)\nCaused by: java.io.IOException: Unexpected termination of the channel\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)\nCaused by: java.io.EOFException\n\tat java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2353)\n\tat java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2822)\n\tat java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)\n\tat java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)\n\tat hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)\n\tat hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)", "stdout": "Installing git-parameter from update center", "stdout_lines": ["Installing git-parameter from update center"], "warnings": []}

**Comment by lioraspark** [comment]
works with no errors when  jenkins_plugin module used after the role run completed

**Comment by BerndDoser** [comment]
I see the same issue using a vagrant-box bento/ubuntu-16.04. When I browse to the server, I get the page "Unlock Jenkins" for copying the initial administrator password.

How have you moved the jenkins_plugin module behind the jenkins role?

**Comment by lioramilbaum** [comment]
I have created a wrapper playbook which is depended on this one. My customizations are done in the wrapper playbook, after the dependency is fulfilled.

**Comment by dizeee** [comment]
As far as I can see that happens to plugins with yet unresolved dependencies. The plugin is being installed with dependencies resolved as expected though. So the error happens after that. I tried both stable (2.32.2) and weekly (2.50) builds.

You can list all dependencies in jenkins_plugins as a workaround, though it's quite a pain.

Some issues that seem related:
https://issues.jenkins-ci.org/browse/JENKINS-23232
https://issues.jenkins-ci.org/browse/JENKINS-40056
http://stackoverflow.com/questions/36929484/jenkins-severe-i-o-error-in-channel-chunked-connection

**Comment by dizeee** [comment]
I found a much better workaround with Ansible jenkins_plugin module, which works like a charm!

https://docs.ansible.com/ansible/jenkins_plugin_module.html

**Comment by geerlingguy** [comment]
@dizeee - Ah, I'd not seen that module before. It might be good to simply use it in this role too!

**Comment by dizeee** [comment]
@geerlingguy I'm playing around with it right now and I could make a pull request in a day or two. Do you want me to keep the current code for backward compatibility with Ansible < 2.2?

**Comment by geerlingguy** [comment]
@dizeee - I'd rather just make a clean break and bump the meta/main.yml minimum version to `2.2`. This change would require the role to go through a major version bump, but that's fine by me. Simplicity/maintainability > legacy support.

**Comment by dizeee** [comment]
@geerlingguy Perfect!

**Comment by geerlingguy** [comment]
I'm testing @dizeee's PR now, will hopefully be able to merge it shortly.
