### ISSUE TITLE
Installation doesn't work when hostname is accessible via https only

### ISSUE THREAD

**Issue by jurajseffer** [geerlingguy/ansible-role-jenkins#111]
```
shell: "curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/"
```
This assumes http is always available. Since the playbook runs on the target server, I suggest changing `http://{{ jenkins_hostname }}` to `http://localhost` or provide an option to configure the protocol.

**Comment by bbaassssiiee** [comment]
A change to http://localhost would suffice here.
