### ISSUE TITLE
Add support for updating jenkins

### ISSUE THREAD

**Issue by sgautrin** [geerlingguy/ansible-role-jenkins#112]
Use case:

- I manage my jenkins installation with a playbook using this role
- I installed it a week ago or so
- Now there's a new LTS version of jenkins available
- Running the playbook again will update the apt cache, but will not update jenkins

This is due to the task “Install Jenkins from repository.” (both apt and rpm versions) which only request the package to be installed. Switching to “latest” would upgrade the package if a new version is available.

It might not be the best for everyone, so maybe an option could be added to select the behaviour between “installed” and “latest”.

**Comment by geerlingguy** [comment]
@sgautrin - Yeah, I have this option available in many of my other playbooks—basically something like `jenkins_package_state` and it could be any of Ansible's options, defaulting to `present`. If you set `latest` then it would always try to update.

**Comment by leifmadsen** [comment]
I like this option a lot, as we've had a discussion internally about this as well. Sounds like this would be relatively easy to implement. I might try and provide a patch here in the next day or so. I'll look at the other @geerlingguy playbooks and try to implement it in a similar manner so things are consistent.

**Comment by yakhyadabo** [comment]
Is there any way to upgrade to a specific version of Jenkins (2.57 for example)?

**Comment by fields** [comment]
Is there a workaround in the meantime?

**Comment by sgautrin** [comment]
> Is there a workaround in the meantime? Can I just do `yum upgrade jenkins` from the machine?

For my playbook targeting a debian, I just have a task in the main playbook specifying

```
apt: name=jenkins state=latest
```

An equivalent for Red Hat and `yum` would work as well, and of course a direct command as well (but might as well use the apt/yum modules for that).

```
yum: name=jenkins state=latest
```

**Comment by fields** [comment]
@sgautrin you should switch to using the generic `package` module: http://docs.ansible.com/ansible/package_module.html

**Comment by yakhyadabo** [comment]
What to do if I want to upgrade to a given version of Jenkins, not the latest?
I've set **jenkins_version** to **"2.69"** but it's not enough. I'm still running a previous version.

**Comment by yakhyadabo** [comment]
It looks like I have to implement this update manually: 
 - run a play to remove Jenkins
 - replay the playbook with the new version of Jenkins

**Comment by geerlingguy** [comment]
@yakhyadabo - You should be able to upgrade the version starting a couple point releases of this role ago, just by bumping the `jenkins_version`: https://github.com/geerlingguy/ansible-role-jenkins/blob/master/tasks/setup-Debian.yml#L20-L37

But if you're using the package-based install (e.g. you don't have `jenkins_version` set), you don't have much control—the package will either be the version that was available the first time your playbook was run, or the latest version if you use `latest` to always upgrade when the playbook runs.
