### ISSUE TITLE
Ansible wait_for not working as expected

### ISSUE THREAD

**Issue by tylerturk** [geerlingguy/ansible-role-jenkins#12]
Howdy,

As discussed on twitter, the wait_for module is just waiting for the TCP socket to start accepting connections which does not ensure that the Java app has finished starting. With a quick search, I found another method that would help mitigate failures on downloading the jenkins CLI.

http://stackoverflow.com/questions/23919744/how-to-restart-jenkins-using-ansible-and-wait-for-it-to-come-back

**Comment by geerlingguy** [comment]
Above PR was merged, so this issue is fixed. Thanks, @tylerturk !
