### ISSUE TITLE
[feature] add ability to pin jenkins plugins

### ISSUE THREAD

**Issue by leifmadsen** [geerlingguy/ansible-role-jenkins#122]
Currently when deploying Jenkins with this role, if you specify a list of plugins to be installed, you're unable to pin them to a version so that your environment is reproducible.

The PR from @dizeee in #119 looks to be a great basis of adding this functionality.

I would expect the functionality to slightly change the format of the plugins list, from a simple list, to a list of hashes. For example:

```
- { name: build-timeout, version: 1.18 }
- { name: copy-to-slave, version: 1.4.4 }
```

I'm happy to supply a PR with the changes if we can agree on adding this functionality, and the format for plugin defines in the vars files.

CC: @geerlingguy, @dizeee

**Comment by geerlingguy** [comment]
@leifmadsen - Looks good to me. As long as you can just supply a name and that means 'install latest version'.

**Comment by lioramilbaum** [comment]
Here is a code snippet of how I have implemented this feature:

- name: Install plugins
  jenkins_plugin:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    params: "{{ my_jenkins_params }}"
  with_items: 
  - "{{ my_jenkins_plugins }}" 
  notify: restart jenkins


  "my_jenkins_plugins": [
    {
      "name": "structs",
      "version": "1.6"
    },
    {
      "name": "junit",
      "version": "1.20"
    }
]

**Comment by leifmadsen** [comment]
Thanks much @lioramilbaum! I'll see what I can muster in the next couple of weeks. Unfortunately this had to drop in priority for me this week since I'm on PTO next week.

**Comment by shanedroid** [comment]
Just sharing what ended up working for me to be able to handle plugins for Jenkins using a wrapper role:

https://gist.github.com/shanedroid/b9ffd39417c0c799481fb275392901bb

**Comment by tomaszkrzyzanowski** [comment]
Hi!
@geerlingguy it is possible to merge this functionality? As i see there are duplicated issues and PRs for this functionality
Issue: https://github.com/geerlingguy/ansible-role-jenkins/issues/267
PRs: 
https://github.com/geerlingguy/ansible-role-jenkins/pull/260
https://github.com/geerlingguy/ansible-role-jenkins/pull/194
https://github.com/geerlingguy/ansible-role-jenkins/pull/157

This PRs are backward compatibe (you are able to type only name as a string):
https://github.com/geerlingguy/ansible-role-jenkins/pull/194
https://github.com/geerlingguy/ansible-role-jenkins/pull/157

@geerlingguy I can fix conflicts in one of the branches, but we need your help with eventual merge ;)

Regards

**Comment by gone-skiing** [comment]
I opened the 194 a while ago. Happy to resolve the conflicts if @geerlingguy is open to merging. Just let me know. Seems like this is something that people would find useful (given number of duplicated efforts to solve the same problem ;-)).

**Comment by gone-skiing** [comment]
@tomaszkrzyzanowski #194 has just been merged. We can probably close this one.

**Comment by geerlingguy** [comment]
Yep! Thanks for mentioning it. I'll close this issue now.

Just tagged 4.0.0 which has this feature.
