### ISSUE TITLE
How to automate the configuration of installed plugins in this role? 

### ISSUE THREAD

**Issue by jkumar10** [geerlingguy/ansible-role-jenkins#123]
What existing changes need to be made in the tasks and vars?

**Comment by irinabov** [comment]
You can redefine jenkins_plugins, and use it with the role, for example:
-
roles:
    - { role: geerlingguy.jenkins, jenkins_plugins: ['ant', 'authentication-tokens'], tags: [ 'jenkins' ] }

**Comment by jk1093** [comment]
@irinabov Please can you paste a sample task here and show me. Do I need to create a separate tasks for each plugin?

**Comment by wilcollins** [comment]
I believe @irinabov misunderstood the question because that is the standard use of the role and does not provide any additional plugin configuration.

This feature is much needed though!

**Comment by wilcollins** [comment]
duplicate of https://github.com/geerlingguy/ansible-role-jenkins/issues/85

**Comment by lioramilbaum** [comment]
create a wrapper playbook and use groovy to configure the plugins.

**Comment by shanedroid** [comment]
Just sharing what ended up working for me to be able to handle plugins for Jenkins using a wrapper role:

https://gist.github.com/shanedroid/b9ffd39417c0c799481fb275392901bb

**Comment by devantoine** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin
