### ISSUE TITLE
Problem with admin user login

### ISSUE THREAD

**Issue by irinabov** [geerlingguy/ansible-role-jenkins#125]
I am running on Fedora 25 with ansible-2.2.1.0-1.fc25.noarch and installing jenkins-2.53-1.1.noarch rpm using geerlingguy.jenkins role. Upon its completion I cannot login into jenkins site using "admin, admin" user and password. It also fails to install plugins (because admin password is wrong, it is still set to its "initial" secret). However, if I change roles/geerlingguy.jenkins/defaults/main.yml to this:

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }} --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin"

then everything works as expected (plugins are installed and login is OK).

**Comment by irinabov** [comment]
However if you want to require user login, you need to change this in config.xml:

  <authorizationStrategy class="hudson.security.AuthorizationStrategy$Unsecured"/>
  <securityRealm class="hudson.security.SecurityRealm$None"/>

to this:
  <authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy"/>
  <securityRealm class="hudson.security.HudsonPrivateSecurityRealm">

**Comment by jk1093** [comment]
Make changes in the groovy script under templates folder as : 

#!groovy
import hudson.security.*
import jenkins.model.*

def instance = Jenkins.getInstance()
def hudsonRealm = new HudsonPrivateSecurityRealm(false)
def users = hudsonRealm.getAllUsers()
users_s = users.collect { it.toString() }
if ("{{ jenkins_admin_username }}" in users_s) {
    println "Admin user already exists"
} else {
    println "--> creating local admin user"

    hudsonRealm.createAccount('{{ jenkins_admin_username }}', '{{ jenkins_admin_password }}')
    instance.setSecurityRealm(hudsonRealm)

    def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
    instance.setAuthorizationStrategy(strategy)
    instance.save()
}

**Comment by irinabov** [comment]
The above suggestion did not work for me.

**Comment by sreekanth-manda** [comment]
It didn't work for me either, when i try to login with admin/admin i am getting 'Invalid login information. Please try again.'

**Comment by jk1093** [comment]
https://github.com/geerlingguy/ansible-role-jenkins/issues/79 

Please follow the above thread.

**Comment by geerlingguy** [comment]
Yep, closing this in favor of #79. I'm going to test it and fix if that's the fix in a few minutes.
