### ISSUE TITLE
Cant access jenkins server from VM ip

### ISSUE THREAD

**Issue by maddieminnick** [geerlingguy/ansible-role-jenkins#145]
Hello, 

So i have set up a n Ubuntu 16.04 vagrant VM and used this ansible role to set up jenkins. I have set a public_network ip in my vagrant file. I can access the jenkins server from my host machines ip followed by 8080. However, when I try to use the VM ip I set up followed by 8080, I cannot access jenkins. Is it possible to set up the box so that I can access the jenkins server using the IP? I do not want to use a hostonly/private network ip, because I need to access the jenkins server from git to use a hook.

I followed this tutorial to set up vagrant with your ansible-galaxy.
http://codeheaven.io/an-introduction-to-ansible/

When I ssh into the machine, configuring the IP has worked since enpos8 has the correct inet addr.
![screenshot from 2017-06-13 10-04-00](https://user-images.githubusercontent.com/21375513/27092239-e760d03e-501f-11e7-9c53-9ba54f522101.png)

![screenshot from 2017-06-13 10-04-38](https://user-images.githubusercontent.com/21375513/27092243-e87f567a-501f-11e7-8ac8-9e5d61e2088c.png)
![screenshot from 2017-06-13 10-05-02](https://user-images.githubusercontent.com/21375513/27092247-ea11b320-501f-11e7-8d74-64b30bd27c81.png)

**Comment by geerlingguy** [comment]
@maddieminnick - If you're using a bridged public_network... that can get really tricky in terms of trying to make it work with accessing your VM directly vs. your host machine.

I almost always use private networks with my VMs (example: https://github.com/geerlingguy/ansible-vagrant-examples/blob/master/jenkins/Vagrantfile#L20), and I think any questions/issues there would have to be directed at upstream projects, like Vagrant (https://github.com/mitchellh/vagrant/issues) or VirtualBox (https://forums.virtualbox.org).

The configuration of networking in Vagrant (and, by extension, VirtualBox) is a pretty beefy topic in and of itself, and I can't really help much in terms of that aspect—if you want to try out my Jenkins example VM (https://github.com/geerlingguy/ansible-vagrant-examples/tree/master/jenkins), see if that works—and if it doesn't, please open an issue in that repository with details of how to reproduce the error.
