### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by mhitza** [geerlingguy/ansible-role-jenkins#15]
I'm working in a private fork to configure SSL for jenkins. For this there are two major changes that have to be done, and different ways to do them; but I'd like your feedback on them since I would want to merge the changes back when I'm done.

**/etc/sysconfig/jenkins variable updates**
I'm thinking of a template file with default values (jenkins_config_* named variables)

**Configurable protocol and port**
During the plugin installation http is used and the 8080 port. Might have two variables `jenkins_protocol` and `jenkins_port`; maybe reuse the `jenkins_config_https_port` (if set) from the configuration setup instead of having two variables do the same thing?

**Comment by mhitza** [comment]
After seeing PR #3 I think only maybe overwrites should be left up to the users with `lineinfile` and similar tasks, since the configuration format varies wildly between Debian/Redhat.

Or do you think it should include them both with all options, or only the common subset of configuration parameters?

**Comment by geerlingguy** [comment]
Closing this in favor of #13 — I'm considering adding a template that will somehow work cross-platform (at least on Debian/CentOS), or having a template per-platform... but I'd like to figure out a robust way to do this, at least better than `lineinfile`
