### ISSUE TITLE
Option to add init.groovy.d scripts

### ISSUE THREAD

**Issue by sebastianludwig** [geerlingguy/ansible-role-jenkins#151]
I currently need to setup a Jenkins with some init.groovy.d scripts. I'd be nice to be able to give a list of files to the jenkins role. Currently I've to wait for the installation to finish, add the scripts, restart Jenkins, wait for it to start up (duplicating the role tasks) and then proceed with adding jobs etc.

Would you accept a PR for this?

P.S. awesome role, thank you very much 👍

**Comment by geerlingguy** [comment]
Yes; if it were something simple like a task that would run a list of groovy scripts, and possibly also with an example script that we can run in one of the Travis CI tests, then I'd be willing to add that in.
