### ISSUE TITLE
Can't install plugins using password

### ISSUE THREAD

**Issue by kmcquade** [geerlingguy/ansible-role-jenkins#152]
Hi,

My build is stuck on the task titled "Install Jenkins plugins using password" and I haven't been able to fix it. Could you take a look at my playbook and let me know where I am going wrong? It would be really helpful if you could have an example-playbooks directory here, other than just providing a basic playbook for local instances.

**My playbook**:
---
- name: Install jenkins
  hosts: legit-host-reference
  vars:
    jenkins_hostname: legit.hostname
    jenkins_plugins:
      - greenballs
      - azure-credentials
      - copy-to-slave
      - docker-plugin
      - email-ext
      - git
      - mailer
      - maven-plugin
      - slack
      - ssh-agent
      - azure-vm-agents
      - copy-to-slave
      - mailer
      - ssh
      - windows-azure-storage
      - timestamper
      - tfs
    jenkins_home: /tmp/jenkins
    jenkins_plugin_timeout: 120
    jenkins_connection_delay: 5
    jenkins_connection_retries: 60
    jenkins_jar_location: /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar
    jenkins_admin_username: admin
    jenkins_admin_password: admin
  roles:
  - geerlingguy.jenkins

**Directory and file setup**:

/
/jenkins.yml
/jenkins-configs/
/jenkins-configs/config.xml ## Jenkins config
/jenkins-configs/jobs/jobname
/jenkins-configs/jobs/jobname/config.xml ## Job config

**Error message on task**:

failed: [legit.hostname] (item=greenballs) => {"details": "Request failed: <urlopen error timed out>", "failed": true, "item": "greenballs", "msg": "Cannot get CSRF"}

**Comment by geerlingguy** [comment]
Hmm, this looks like it's not seeing Jenkins actually started up, or it's not able to connect to Jenkins for some other reason; see https://stackoverflow.com/questions/42219781/gets-error-cannot-get-csrf-when-trying-to-install-jenkins-plugin-using-ansible

On the same server, if you `curl legit.hostname:8080`, does it return the Jenkins login redirection?

**Comment by kmcquade** [comment]
Issue resolved. I was creating this in Azure VMs and it was an issue with the Network Security Group rules. Needed to permit port 8080 traffic as a custom NSG rule, as the default HTTP rule is port 80.

Thanks for taking a look at it. Curling the hostname did help us troubleshoot. Really happy about this!
