### ISSUE TITLE
Same plugin gets installed everytime

### ISSUE THREAD

**Issue by qageek** [geerlingguy/ansible-role-jenkins#158]
During the test provisioning; installed "nodelabelparameter" plugin. For the later runs, changed the plug-in to "build-pipeline-plugin"; however every time only the prior gets installed.

../defaults/main.yml:
jenkins_plugins: ["build-pipeline-plugin"]

Extract from the playbook output:

`changed:` [IP_ADDR] => (item=nodelabelparameter) => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "backup": null, 
            "content": null, 
            "delimiter": null, 
            "directory_mode": null, 
            "follow": false, 
            "force": false, 
            "force_basic_auth": true, 
            "group": "jenkins", 
            "http_agent": "ansible-httpget", 
            "jenkins_home": "/var/lib/jenkins", 
            "mode": "0644", 
            "name": "nodelabelparameter", 
            "owner": "jenkins", 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "state": "present", 
            "timeout": 30.0, 
            "unsafe_writes": null, 
            "updates_expiration": 86400, 
            "updates_url": "https://updates.jenkins-ci.org", 
            "url": "http://myjenkins:8080/master", 
            "url_password": "admin", 
            "url_username": "admin", 
            "use_proxy": true, 
            "validate_certs": true, 
            "version": null, 
            "with_dependencies": true
        }, 
        "module_name": "jenkins_plugin"
    }, 
    "item": "nodelabelparameter", 
    "plugin": "nodelabelparameter", 
    "state": "present"
}

**Comment by geerlingguy** [comment]
Is it possible you have `jenkins_plugins` defined elsewhere? If you only have it defined in one place, and it's installing a different list of plugins, then either fact caching may be causing issues (do you use fact caching?), there's another variable defined somewhere in the playbook, vars, or inventory, or Ansible core has a bug—but I doubt the latter since I've been working on a few Jenkins playbooks this week and didn't see the problem (using Ansible 2.3.1).
