### ISSUE TITLE
jenkins escapping plugin installation using admin token file

### ISSUE THREAD

**Issue by pritha-intelliB** [geerlingguy/ansible-role-jenkins#162]
Hi ,

Jenkins is always skipping plugins is the admin token has to be taken from file

**Comment by geerlingguy** [comment]
I'm not quite sure what you mean here... I'm using the role right now and have not had any issues with the plugins defined in `jenkins_plugins` being installed.

Can you provide an example configuration that's failing, or steps to reproduce the issue you're seeing? Without that, I don't know what I can do.

**Comment by pritha-intelliB** [comment]
Hi Jeff,

please find below my playbook snippet

- name: Install Jenkins
  hosts: localhost
  vars:
    jenkins_version: "2.73"
    jenkins_package_state: present
    jenkins_hostname: localhost
    jenkins_http_port: 8080
    jenkins_admin_token_file: "/var/lib/jenkins/users/admin/config.xml"
    jenkins_plugins:
         - workflow-multibranch
          - git
   roles:
    - role: geerlingguy.jenkins
      become: true

As I am trying to take the token from a file the role is escaping the
plugins

**Comment by pritha-intelliB** [comment]
- name: Install Jenkins
  hosts: localhost
  no_log: false
  vars:
    jenkins_version: "2.73"
    jenkins_package_state: present
    jenkins_hostname: localhost
    jenkins_http_port: 8080
    jenkins_admin_username: admin
    jenkins_admin_token_file: "/var/lib/jenkins/users/admin/config.xml"
    jenkins_plugins:
         - workflow-multibranch
          - git

   roles:
    - role: geerlingguy.jenkins
      become: true

this is the playbook snippet

**Comment by pritha-intelliB** [comment]
hi jeff,

I have found that plugins.yml needs to be updated to work with password files. Ansible version 2.3.
I have fixed that part. let me know how I can send that for your review

Thanks,
Pritha
