### ISSUE TITLE
Wait for Jenkins to start up before proceeding

### ISSUE THREAD

**Issue by esxi1979** [geerlingguy/ansible-role-jenkins#163]
hello

i ran it on my brand new RHEL 6x box & it stuck on below

FYI there is RHEl repo on box already 

PLAY [my-jenkins] ******************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************
ok: [server1]

TASK [geerlingguy.java : Include OS-specific variables.] ***************************************************************************************************
ok: [server1]

TASK [geerlingguy.java : Include version-specific variables for Ubuntu.] ***********************************************************************************
skipping: [server1]

TASK [geerlingguy.java : Define java_packages.] ************************************************************************************************************
ok: [server1]

TASK [geerlingguy.java : Ensure Java is installed.] ********************************************************************************************************
ok: [server1] => (item=[u'java-1.7.0-openjdk'])

TASK [geerlingguy.java : Update apt cache.] ****************************************************************************************************************
skipping: [server1]

TASK [geerlingguy.java : Ensure Java is installed.] ********************************************************************************************************
skipping: [server1] => (item=[])

TASK [geerlingguy.java : Ensure Java is installed.] ********************************************************************************************************
skipping: [server1] => (item=[])

TASK [geerlingguy.java : ensure proc is mounted] ***********************************************************************************************************
skipping: [server1]

TASK [geerlingguy.java : ensure fdesc is mounted] **********************************************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Include OS-Specific variables] *************************************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Define jenkins_repo_url] *******************************************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Define jenkins_repo_key_url] ***************************************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Define jenkins_pkg_url] ********************************************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Ensure dependencies are installed.] ********************************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Ensure Jenkins repo is installed.] *********************************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Add Jenkins repo GPG key.] *****************************************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Download specific Jenkins version.] ********************************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Check if we downloaded a specific version of Jenkins.] *************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Install our specific version of Jenkins.] **************************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Ensure Jenkins is installed.] **************************************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Ensure dependencies are installed.] ********************************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Add Jenkins apt repository key.] ***********************************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Add Jenkins apt repository.] ***************************************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Download specific Jenkins version.] ********************************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Check if we downloaded a specific version of Jenkins.] *************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Install our specific version of Jenkins.] **************************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Ensure Jenkins is installed.] **************************************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Modify variables in init file] *************************************************************************************************
ok: [server1] => (item={u'option': u'JENKINS_ARGS', u'value': u'--prefix='})
ok: [server1] => (item={u'option': u'JENKINS_JAVA_OPTIONS', u'value': u'-Djenkins.install.runSetupWizard=false'})

TASK [geerlingguy.jenkins : Set the Jenkins home directory] ************************************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Immediately restart Jenkins on init config changes.] ***************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Set HTTP port in Jenkins config.] **********************************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Ensure jenkins_home /var/lib/jenkins exists] ***********************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Create custom init scripts directory.] *****************************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Immediately restart Jenkins on http or user changes.] **************************************************************************
skipping: [server1]

TASK [geerlingguy.jenkins : Ensure Jenkins is started and runs on startup.] ********************************************************************************
ok: [server1]

TASK [geerlingguy.jenkins : Wait for Jenkins to start up before proceeding.] *******************************************************************************
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (60 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (59 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (58 retries left).

above simply get stuck 

TRYING: Wait for Jenkins to start up before proceeding. (40 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (39 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (38 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (37 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (36 retries left).

box has 

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

Please  suggest

**Comment by Gujarats** [comment]
I got the same problem, I got error for : `curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/`. this command will try 60 times as default value.

This problem was arise on my fresh ubuntu server from AWS.
Hopefully somebody can help to solve this problem.

**Comment by akira-baruah** [comment]
Did you specify a custom value for the role variable `jenkins_hostname`?

**Comment by Gujarats** [comment]
@akira-baruah yup this is my jenkins_hostname : 

```yaml
---
# This playbook deploys the whole application stack in this site.
- name: installing jenkins to jenkins node
  hosts: jenkins
  vars:
    jenkins_hostname: my.testing.cm
  hosts: jenkins 
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
  become: true
```

But when I changed the `jenkins_hostname` to `localhost` it works on my remote server. 
Does `jenkins_hostname` should be always localhost ?

**Comment by akira-baruah** [comment]
@Gujarats as you pointed out earlier, the command being run (on the Jenkins host) is:
`curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/`

If `jenkins_hostname` is set to `my.testing.cm`, then curl will try to access `http://my.testing.cm:8080/cli/` (see [default values](https://github.com/geerlingguy/ansible-role-jenkins/blob/master/defaults/main.yml)) from the Jenkins host machine. If `my.testing.cm` doesn't actually resolve to the machine on which you just deployed Jenkins, this command will fail.

**Comment by akira-baruah** [comment]
@esxi1979 is this issue resolved?

**Comment by esxi1979** [comment]
Sorry i did not try it, let me check sometime later , thanks for asking

**Comment by joaoferrao** [comment]
Using 0.0.0.0 instead of localhost fixed it for me.

**Comment by hlarsen** [comment]
by default geerlingguy.java installs java 1.7.0, you need to specify java-1.8.0-openjdk using the `java_packages` var, otherwise jenkins will not start up:

> Aug 21 17:01:06 playbook-testing jenkins[15565]: Starting Jenkins Jenkins requires Java 8, but you are running 1.7.0_191-mockbuild_2018_07_30_15_33-b00 from /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.1...7_5.x86_64/jre

there is a (small) note about Java 8+ in the readme, but considering there are quite a few issues about this, it might be a good idea for the README to be a bit more clear.

**Comment by agardnerIT** [comment]
Same issue on AWS `2018.03.0 (HVM)`. AMI ID: `ami-02fd0b06f06d93dfc`

Here's my playbook. Note, I've also tried `jenkins_hostname: localhost`

```
---
- name: Jenkins
  hosts: aws

  vars:
    jenkins_hostname: 0.0.0.0
    java_packages:
      - java-1.8.0-openjdk

  roles:
    - role: geerlingguy.java
      become: yes

    - role: geerlingguy.jenkins
      become: yes
```
