### ISSUE TITLE
Jenkins plugins NOT installed as expected

### ISSUE THREAD

**Issue by liuchu** [geerlingguy/ansible-role-jenkins#164]
Hi guys,

I run my play book with "geerlingguy.jenkins" role from Ansible galaxy, but found this issue: Jenkins will install and launch perfectly, but plugins can NOT be installed as expected.

See Ansible output and plugin list:
![plugins_install](https://user-images.githubusercontent.com/16880252/30147454-fee2085a-93d0-11e7-8c4c-b6f59c3660ba.png)
![no_plugins](https://user-images.githubusercontent.com/16880252/30147453-fed2c52a-93d0-11e7-8b7b-6ef1e9f376ff.png)

And I did nothing change to my local "geerlingguy.jenkins", just simply include it, see my major play site.yml:

    DASH name: Install Jenkins and its plugins
    hosts: jenkins_servers
    remote_user: root

    vars:
      jenkins_hostname: localhost
      jenkins_plugins:
        - git
        - sonar
        - ssh
        - gerrit-trigger
        - gearman-plugin
        - zmq-event-publisher
        - ansicolor
        - matrix-project
        - workflow-aggregator
        - extended-read-permission
        - ssh-slaves

    roles:
      DASH geerlingguy.jenkins

**Comment by geerlingguy** [comment]
Can you give more environment information? It seems like it's definitely installing plugins, if the status is changed for all of those. Maybe Jenkins just needs to be restarted?

**Comment by cristianburca** [comment]
Same approach at me and facing the same situation even Jenkins get restarted.

**Comment by pigulla** [comment]
Not sure if this has anything to do with the OPs issue, but I can't install plugins either:

```
TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ********************************************************************
failed: [jenkins] (item=active-directory) => {"changed": false, "item": "active-directory", "msg": "The params option to jenkins_plugin was removed in Ansible 2.5since it circumvents Ansible's option handling"}
```

I'm using Ansible 2.5 and `geerlingguy.jenkins` 3.2.2

**Comment by liuchu** [comment]
Operation system: Red Hat Enterprise Linux Server release 7.4 (Maipo)
Kernel: 3.10.0-693.5.2.el7.x86_64
Ansible version: 2.3.0.0
Python version: 2.7.5
SE Linux: Disabled

@geerlingguy 
Every time I re-run the playbook, output always show as "**changed**", looks like Ansible do execute the installation process , but do not effect in the end. Just like we type some content in a file, but always forget to save it, so we always see a empty file and re-type again and again.

Actually we did some tests among several VMs, it works on some VMs. But in most time, it's the case I put forward.

**Comment by liuchu** [comment]
@pigulla Your issue should be with Ansible version know from the error messgae, looks like `geerlingguy.jenkins` is NOT compatible with Ansible 2.5

**Comment by anrizal** [comment]
hello, I also got the same issue. Jenkins is restarted after install. This isssue came after I updated to the latest geerlingguy ubuntu 16 64-bit box.

**Comment by kallaics-liferay** [comment]
1. I have a same issue on Ubuntu 16.04 with Ansible 2.5
2. I run first, all items have been changed status.
3. I checked the installed plugins, then some plugin installed ( sometimes nothing)
4. When I run the playbook again, then it will fix the missing plugins.

**Comment by fedealaimo** [comment]
Hi, 
I am also experiencing the issue that I install with plugins and after the last Jenkins restart the plugins folder is empty (jenkins fails to properly start as it can't find the plugins). Any ideas? 
Thanks, other than that this and many of your other roles work greatly!
