### ISSUE TITLE
Retry of plugin install?

### ISSUE THREAD

**Issue by caphrim007** [geerlingguy/ansible-role-jenkins#169]
Hey @geerlingguy , can a `retries` be added to the plugin installation tasks? Periodically I get a `Connection failure: timedout` associated with a plugin installation that causes that plugin to fail to install and the rest of the playbook to stop.

**Comment by geerlingguy** [comment]
@caphrim007 - I've seen the same behavior in the past; it seems the servers where the plugin information and downloads is hosted are not the most resilient.

One other thing, in the mean time—if you make sure to check for plugin updates prior to running this role and having the plugins installed, it will have the latest mirror data up to date. Sometimes if it's outdated you end up hitting failures every run for certain plugins :(

**Comment by elaurijssens** [comment]
I noticed something similar but slightly different with the latest version: some plugins cause Jenkins to reload so installation of subsequent plugins fail. A second run of the playbook that applies the role succeeds as expected.

**Comment by secfigo** [comment]
There is a nice example of how we might be able to handle this issue more gracefully here https://docs.ansible.com/ansible/latest/modules/jenkins_plugin_module.html#examples. It would be nice to get this added into the role.

**Comment by mallikharjuna-ibexlabs** [comment]
Hi, @geerlingguy We are not getting any default plugins for amazon linux, but when we tried with the ubuntu 16, we can able to install the suggested plugins after login into the Jenkins console, May i know the what was caused for this.

**Comment by CloudSurgeon** [comment]
Retry on plugins was added by #252
