### ISSUE TITLE
Debian repo key URL is changed

### ISSUE THREAD

**Issue by hepabolu** [geerlingguy/ansible-role-jenkins#17]
it should be: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key for Latest & Greatest
and http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key for LTS

**Comment by geerlingguy** [comment]
Thanks! I had fixed the RHEL/CentOS vars, but forgot about the Debian vars.
