### ISSUE TITLE
Install Jenkins plugins with password not working due changes in Ansible

### ISSUE THREAD

**Issue by rsanzante** [geerlingguy/ansible-role-jenkins#170]
Ansible now doesn't allow to pass the url_password as param to the jenkins_plugin task. Instead, url_password is passed as task parameter.

I don't know where this was changed in Ansible, but you an see a commit where doc is updated here: 
https://github.com/ansible/ansible/commit/863fcb5aced55fd9ce3080905bd6405c8bfd0511.

**Comment by rsanzante** [comment]
The error message from Ansible is "Do not specify url_password in params as it may get logged".

**Comment by Skunnyk** [comment]
Updating tasks/plugins.yml by setting url_password as a task parameter, and it works.
Do you need a PR for this ? (I'm an ansible padawan so maybe there are good reasons for not updating it yet)

**Comment by rsanzante** [comment]
There's already a PR for this issue: https://github.com/geerlingguy/ansible-role-jenkins/pull/171

**Comment by geerlingguy** [comment]
Fixed via #171 — thanks!
