### ISSUE TITLE
Cannot set timezones on tests

### ISSUE THREAD

**Issue by mdelapenya** [geerlingguy/ansible-role-jenkins#178]
The timezone is not properly set on tests. Not sure if the error comes from the docker container we use to setup the test environment, as I consider this America/Los_Angeles timezone as a valid timezone value.

I sent here a PR verifying the problem: https://github.com/geerlingguy/ansible-role-jenkins/pull/168

Thanks!

**Comment by mdelapenya** [comment]
Hey @geerlingguy, any update on this?

Thanks!

**Comment by pragmaticivan** [comment]
Hi, any news on that?

**Comment by mdelapenya** [comment]
Hey @geerlingguy could you give us an answer? We'd like to continue using your role, but this is a blocker for us, as our own tests are broken because of this timezone problem.

Thanks!

**Comment by kentr** [comment]
@mdelapenya 

I experienced this issue with another playbook (unrelated to Jenkins).

For me, the solution was to ensure that the `tzdata` package is installed in the container.

This was with an Ubuntu Docker image, using the Ansible `timezone` module.
