### ISSUE TITLE
Unable to install git related plugins

### ISSUE THREAD

**Issue by agrawalpoonam08** [geerlingguy/ansible-role-jenkins#18]
Hi,
I am unable to install git related plugins with the code given by you.
While running it is showing blue color as if already installed but when I see in installed plugin tab the plugins are not there in the list.
I am installing git and git-client plugin.
Do I need to don any kind of update?

Thanks in advance :)

**Comment by geerlingguy** [comment]
Using the configuration:

```yaml
jenkins_plugins:
  - git
```

Successfully installs the git plugin on CentOS 6/7, and Ubuntu 12/14 LTS (I tested just now, and it appears as installed in the UI). I'm thinking it could be that Jenkins never fully restarted, something like that. You can always manually install missing plugins as well, if you need to do so. Better to be in code, but once a Jenkins server is running, a lot of config has to be done by hand anyways :(
