### ISSUE TITLE
Setup wizard appear even when jenkins.install.runSetupWizard=false

### ISSUE THREAD

**Issue by lioramilbaum** [geerlingguy/ansible-role-jenkins#181]
Works for Jenkins up to version 2.93. 
Found a PR which might be relevant: [[FIXES JENKINS-47439] Setup wizard does not resume after restart #3166](https://github.com/jenkinsci/jenkins/pull/3166)

**Comment by lioramilbaum** [comment]
Added the following task right after executing the role to fix it:
- name: fix a defect to disable setup wizard
  jenkins_script:
    script: |
      import static jenkins.model.Jenkins.instance as jenkins
      import jenkins.install.InstallState
      if (!jenkins.installState.isSetupComplete()) {
        InstallState.INITIAL_SETUP_COMPLETED.initializeState()
      }
    user: "{{ admin.userid }}"
    password: "{{ admin.password }}"

**Comment by mkesper** [comment]
This hack works (and is still needed, it seems) with version 2.107.2

**Comment by thongdong7** [comment]
And need to restart jenkins to affect (I got blank page if not restart)

**Comment by Erik-Lamers1** [comment]
Fyi, this will break when using other authentication modes. Like, Github Authentication. As it resets the authentication mode upon Jenkins restart.

**Comment by mkesper** [comment]
Don't understand why, it should only have an effect when Jenkins isn't in state 'installed':
`if (!jenkins.installState.isSetupComplete())`
