### ISSUE TITLE
ValueError: invalid literal for int() with base 10: jenkins_connection_retries

### ISSUE THREAD

**Issue by mclate** [geerlingguy/ansible-role-jenkins#19]
Used example in `README`: 

```yaml
- hosts: local
  vars:
      jenkins_hostname: jenkins.example.com
  roles:
      - { role: geerlingguy.jenkins }
```

With no explicit value for `jenkins_connection_retries` provided, role fails with next exception:

```
fatal: [local] => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 536, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 638, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 841, in _executor_internal_inner
    for x in range(1, int(retries) + 1):
ValueError: invalid literal for int() with base 10: '{{jenkins_connection_retries}}'
```

Wonder if it's missing loading of default variables from `/defaults/main.yml` file...

Ansible: 1.6.6
Role: 
 geerlingguy.java, 1.1.0
 geerlingguy.jenkins, 1.2.4

**Comment by mclate** [comment]
Well, actually it also fails with explicit value defined in the playbook...

**Comment by geerlingguy** [comment]
Hmm... Can you try changing the `jenkins_connection_retries` to `"60"` just to see if there's some strange typing problem? Also, can you update to Ansible 1.9.x (or at least a later version in general)? Maybe there was a bug in 1.6.6. To be honest, I only test on the latest stable release of Ansible, and so even though the role's minimum _should_ be 1.4 or 1.6, I can't guarantee it will work on that old a version.

**Comment by mclate** [comment]
Yes, in fact, it was an issue with an outdated ansible. Sorry i didn't get to it on my own and thank you for pointing it out :)
