### ISSUE TITLE
Can't override the user that the jenkins process runs as

### ISSUE THREAD

**Issue by nhemingway** [geerlingguy/ansible-role-jenkins#192]
The role seems to provide the ability to set "jenkins_process_{user,group}", but this only sets the owner of init.groovy.d

I need (and can hopefully supply a PR) to fix the role to set the process user and file ownerships to an overrideable user/group (defaulting to jenkins:jenkins as currently)

**Comment by nhemingway** [comment]
This, 107 or 210 is needed for those environments where jenkins doesn't run as jenkins.  Happy to resolve the conflicts if there's a chance of getting it merged.

**Comment by nhemingw-xilinx** [comment]
I would reopen this issue, but I don't appear to have the correct access to do so.

**Comment by nhemingw-xilinx** [comment]
This is not stale.  If there is an issue with this issue or the associated PR, please could a comment be left explaining what the the issue is?
