### ISSUE TITLE
Remove strict dependency on geerlingguy.java role

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-jenkins#195]
I can remember that in one of our previous discussions that you would never include dependencies, but this role contains a dependency

**Comment by geerlingguy** [comment]
"Never" is a strong word :)

But I'm willing to consider dropping the role as a strict dependency so people could use their own playbook/role to do all the java setup.

**Comment by rdonkin** [comment]
I would prefer this as well. Currently, `geerlingguy.java` is not installing Java 8 for some reason on Ubuntu 16.04 (fresh server, and no specific role config, just whatever the jenkins role does) - need to submit a bug report on that, but no time right now.

Hence I'm currently using an Oracle Java role instead, and the time spent running geerlingguy.java is wasted.

**Comment by geerlingguy** [comment]
@rdonkin - For the short term, see how this role installs Java 8 on all the different wonderful flavors of OSes: https://github.com/geerlingguy/ansible-role-jenkins/blob/master/tests/java-8.yml

**Comment by 7onetella** [comment]
I am running the jenkins role against Ubuntu 18.04. the dependent java role would install java 11 by default for Ubuntu 18.04. jenkins role install fails. jenkins seems to be expecting java 8. most of the production java apps that I run are not ready for java 11. 

it would be really nice if this dependency is removed.

**Comment by konetzed** [comment]
For now I had to do this to get openjdk-8-jdk installed on Ubuntu 1804.  I figured it might help someone else too. 
`  roles:
      - role: geerlingguy.jenkins
        become: yes
        jenkins_package_state: present
        jenkins_version: "2.176.1"
        jenkins_pkg_url: "http://pkg.jenkins-ci.org/debian-stable/binary/"
        java_packages:
          - openjdk-8-jdk
`

**Comment by geerlingguy** [comment]
Done thanks to #290
