### ISSUE TITLE
File not found: initialAdminPassword 

### ISSUE THREAD

**Issue by simonthaens** [geerlingguy/ansible-role-jenkins#197]
We are trying to build an Amazon AMI with Packer, which needs to be provisioned with Jenkins LTS (2.89.4). We've set up a CodeBuild project for this but the provisioning keeps failing at 'Get Jenkins admin token from file'. 

The strange thing is, if we use our playbook against an ordinary EC2 instance, it succeeds sometimes. Other times we get the same error. This happens both with Ubuntu 16.04 and Centos 7. We've set the parameter 'Jenkins.Install.runSetupWizard = true' because we need our Jenkins to be secure. 

`0;32m amazon-ebs: <127.0.0.1> (0, '\n
{
    "msg": "file not found: /var/lib/jenkins/secrets/initialAdminPassword",
    "failed": true,
    "invocation": {
        "module_args": {
            "src": "/var/lib/jenkins/secrets/initialAdminPassword"
        }
    }
}`

Things we've tried:
-Add a sleep before it starts looking for the InitialAdminPassword file
-Restart the Jenkins service
-Add a task which searches the file system for any file that ends with '*AdminPassword'. This returns nothing.

Can someone help us to resolve this problem? We really don't know what causes this issue. 

EDIT: We managed to successfully create one ami. However, if we run the same code again, it fails. Looks like the success rate is about 10%.

**Comment by geerlingguy** [comment]
Where are you seeing the message:

```
0;32m amazon-ebs: <127.0.0.1> (0, '\n { "msg": "file not found: /var/lib/jenkins/secrets/initialAdminPassword", "failed": true, "invocation": { "module_args": { "src": "/var/lib/jenkins/secrets/initialAdminPassword" } } }
```

Is that in the /var/log/jenkins/jenkins.log file or somewhere else?

If you have the setup wizard set to run in the jenkins_java_options, then it should run, and you can verify if it does at the end of the jenkins.log file.

**Comment by smriyaz391** [comment]
We are also facing the same issue and the log is not generated for initial admin password file

**Comment by richadua** [comment]
Has this been resolved? I am facing this issue too.
