### ISSUE TITLE
ansible-lint complains about curl and get_url module

### ISSUE THREAD

**Issue by dobber** [geerlingguy/ansible-role-jenkins#20]
ansible-lint site.yml
[ANSIBLE0006] curl used in place of get_url module
/var/lib/jenkins/jobs/infrastructure/workspace/ansible/roles/geerlingguy.jenkins/tasks/main.yml:0
Task/Handler: Wait for Jenkins to start up before proceeding.

[ANSIBLE0006] curl used in place of get_url module
/var/lib/jenkins/jobs/infrastructure/workspace/ansible/roles/geerlingguy.jenkins/tasks/plugins.yml:0
Task/Handler: Update Jenkins plugin data.

**Comment by geerlingguy** [comment]
`ansible-lint` is a bit heavy-handed, imo. Sometimes it's a lot simpler (and even cleaner) to use `curl`, especially when you need to run a command with pipes, etc. Doing this using `get_url` would make for a lot more configuration, and the role would be overly complicated (IMO).

**Comment by geerlingguy** [comment]
Reopening; I may be able to use the `uri` module instead... https://github.com/willthames/ansible-lint/issues/70

**Comment by geerlingguy** [comment]
Closing again—once we go full 2.0, I might add the new 'ignore warnings' modifier to those tasks, as the way they're written, it would be difficult to switch to using a different technique... not impossible, but not something I want to spend a couple hours debugging.
