### ISSUE TITLE
Cannot install plugin. workflow-aggregator Connection failure: timed out

### ISSUE THREAD

**Issue by cosmaprc** [geerlingguy/ansible-role-jenkins#213]
I get this error when I run `vagrant up --provision`

TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ***********
changed: [jenkins] => (item=sonar)
changed: [jenkins] => (item=nexus-artifact-uploader)
changed: [jenkins] => (item=ansible)
failed: [jenkins] (item=workflow-aggregator) => {"changed": false, "details": "Connection failure: timed out", "item": "workflow-aggregator", "msg": "Cannot install plugin."}
changed: [jenkins] => (item=slack)
changed: [jenkins] => (item=slack-uploader)
changed: [jenkins] => (item=git)
changed: [jenkins] => (item=github)
changed: [jenkins] => (item=credentials-binding)
changed: [jenkins] => (item=pipeline-utility-steps)
changed: [jenkins] => (item=disk-usage)
changed: [jenkins] => (item=ws-cleanup)
        to retry, use: --limit @/vagrant/ansible/alm.retry

**Comment by geerlingguy** [comment]
@cosmaprc if you try again, does it have the same failure? And if you go into the Jenkins UI and try installing there, does it succeed?

**Comment by cosmaprc** [comment]
@geerlingguy If I run vagrant destroy then vagrant up --provision on https://github.com/ricardozanini/vagrant-alm I get the error every time.

If I run vagrant halt, vagrant up --provision again without vagrant destroy, I get this:
TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ***********
ok: [jenkins] => (item=sonar)
ok: [jenkins] => (item=nexus-artifact-uploader)
ok: [jenkins] => (item=ansible)
ok: [jenkins] => (item=workflow-aggregator)
ok: [jenkins] => (item=slack)
ok: [jenkins] => (item=slack-uploader)
ok: [jenkins] => (item=git)
ok: [jenkins] => (item=github)
ok: [jenkins] => (item=credentials-binding)
ok: [jenkins] => (item=pipeline-utility-steps)
ok: [jenkins] => (item=disk-usage)
ok: [jenkins] => (item=ws-cleanup)

TASK [geerlingguy.jenkins : Install Jenkins plugins using token.] **************
skipping: [jenkins] => (item=sonar)
skipping: [jenkins] => (item=nexus-artifact-uploader)
skipping: [jenkins] => (item=ansible)
skipping: [jenkins] => (item=workflow-aggregator)
skipping: [jenkins] => (item=slack)
skipping: [jenkins] => (item=slack-uploader)
skipping: [jenkins] => (item=git)
skipping: [jenkins] => (item=github)
skipping: [jenkins] => (item=credentials-binding)
skipping: [jenkins] => (item=pipeline-utility-steps)
skipping: [jenkins] => (item=disk-usage)
skipping: [jenkins] => (item=ws-cleanup)

Now if I go to jenkins, run check now to update the plugin info and search for it in available/Installed plugins, I can't find it, but If I download the latest .hpi file from https://updates.jenkins.io/download/plugins/workflow-aggregator/ and try to install it, I get:

"workflow-aggregator	 workflow-aggregator plugin is already installed. Jenkins needs to be restarted for the update to take effect" - Restarting has no effect.

Installed jenkins version is "Jenkins ver. 2.120". I'm guessing it's an issue with the plugin ?

**Comment by mkesper** [comment]
The role should retry a configurable amount of times if a plugin install runs on timeout.

**Comment by albohlabs** [comment]
Use the `jenkins_plugin_timeout` variable. Have a look at [/tests/test-plugins.yml](https://github.com/geerlingguy/ansible-role-jenkins/blob/master/tests/test-plugins.yml).
