### ISSUE TITLE
HTTP POST required for plugins since 2018-05-09

### ISSUE THREAD

**Issue by mkesper** [geerlingguy/ansible-role-jenkins#214]
At once I get in a working setup (literally retriggering a Jenkins build from 2018-05-07):

```
TASK [geerlingguy.jenkins : Install Jenkins plugins
using password.] *********** failed: [my-jenkins-01] (item=ansicolor) =>
{"changed": false, "details": "HTTP Error 401: Invalid password/token for user:
admin", "item": "ansicolor", "msg": "Cannot get CSRF"}
```

This seems to be required since the 2018-05-09 release.
https://jenkins.io/security/advisory/2018-05-09/
SECURITY-794 / CVE pending

**Comment by mkesper** [comment]
jenkins_plugin method doesn't support method=POST...

**Comment by mkesper** [comment]
Testing versions: 2.107 / 2.107.2 were working.

**Comment by geerlingguy** [comment]
@mkesper - What do you have set for `jenkins_init_changes`?

**Comment by geerlingguy** [comment]
@mkesper you may want to add to that list:

```
  - option: "JENKINS_JAVA_OPTIONS"
    value: "{{ jenkins_java_options }}"
```

**Comment by mkesper** [comment]
I do not gave found the fitting Java options, it seems. Did try:
`jenkins_java_options: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"`
