### ISSUE TITLE
Container Enabled

### ISSUE THREAD

**Issue by tomasquith** [geerlingguy/ansible-role-jenkins#216]
Hi @geerlingguy 

Thanks for putting this module together, it's making my first venture into ansible much easier.

I'm trying to run this with ansible-container, but I understand it's not designed for it - it's using systemctl on EL etc. 

I've forked it to try and make it container enabled, however I'm having issues running this under ansible-container. 

Have you had any success with using this module in an EL7 container?

**Comment by geerlingguy** [comment]
@tomasquith - Thanks for posting this issue; my goal for this role is to manage Jenkins in environments where systemd is available and the service is managed traditionally.

Other container-based configurations may work and might be possible using this role, but I usually use the official Jenkins Docker images when running Jenkins in container infra, and recommend doing that.
