### ISSUE TITLE
get_url half succeeds

### ISSUE THREAD

**Issue by ronaldpetty** [geerlingguy/ansible-role-jenkins#217]
Hello.

Any advice on what it means for the download to succeed but then it is immediately deleted (before the copy from the tmp file).  Oddly enough, I ran get_url on its own and it worked.  But when running it in the role I see the following.  I suspect I missed something, but not sure what.

```
TASK [geerlingguy.jenkins : Download specific Jenkins version.] ****************************************************************************************************************
task path: /home/user/project/roles/geerlingguy.jenkins/tasks/setup-Debian.yml:21
changed: [ci-server] => {"changed": true, "dest": "/tmp/jenkins_2.122_all.deb", "msg": "OK (74159256 bytes)", "src": "/tmp/tmprw6epv3y", "state": "absent", "url": "http://mirrors.jenkins.io/debian//jenkins_2.122_all.deb"}
```

What I see on the CI server as it runs (downloading to tmp file, but then it is immediately deleted before the moving to destination.

```
ubuntu@ip-10-0-0-65:~$ sudo inotifywait -m -r /tmp
...
/tmp/ MODIFY tmpn7_hjp07
/tmp/ MODIFY tmpn7_hjp07
/tmp/ MODIFY tmpn7_hjp07
/tmp/ MODIFY tmpn7_hjp07
/tmp/ MODIFY tmpn7_hjp07
/tmp/ CLOSE_WRITE,CLOSE tmpn7_hjp07
/tmp/ DELETE tmpn7_hjp07
/tmp/ OPEN,ISDIR ansible_o8fdzor4
/tmp/ansible_o8fdzor4/ OPEN,ISDIR 
/tmp/ansible_o8fdzor4/ OPEN,ISDIR 
/tmp/ ACCESS,ISDIR ansible_o8fdzor4
/tmp/ansible_o8fdzor4/ ACCESS,ISDIR 
/tmp/ ACCESS,ISDIR ansible_o8fdzor4
/tmp/ansible_o8fdzor4/ ACCESS,ISDIR 
/tmp/ansible_o8fdzor4/ DELETE ansible_modlib.zip
/tmp/ansible_o8fdzor4/ DELETE ansible_module_get_url.py
...
```

**Comment by geerlingguy** [comment]
The URL looks a little weird... `http://mirrors.jenkins.io/debian//jenkins_2.122_all.deb`

Maybe it's hitting a 404 or a 302 isn't being handled correctly?

**Comment by ronaldpetty** [comment]
Hi @geerlingguy, thanks for the quick response.

I just figured it out.  I did the original URL and for some reason it didn't work.  Then I added `--check` which causes `get_url` to short-circuit.  Because of the short-circuiting I ended up on wild goose chase hunting it down to find out `--check` was actually causing it.  Not sure what I did wrong in the very beginning.  Now it is working.  The double slash is valid in UNIX, and it seems to work on HTTP as well.  I assume it the config file has a trailing slash.  

```
  vars:
    jenkins_version: "2.122"
#    jenkins_pkg_url: "http://pkg.jenkins-ci.org/debian/"
    jenkins_pkg_url: "http://mirrors.jenkins.io/debian/"
```

Thanks again, and nice work!

**Comment by geerlingguy** [comment]
@ronaldpetty - Very strange, but it's one of those weird things I've seen in other places before, so why not here? :D
