### ISSUE TITLE
i have one problem in jenkins please help me

### ISSUE THREAD

**Issue by audireddy503** [geerlingguy/ansible-role-jenkins#219]
![capture](https://user-images.githubusercontent.com/33023481/40529566-204f5f24-6013-11e8-8884-2cd86175a323.PNG)

**Comment by audireddy503** [comment]
this is my problem ple help me

**Comment by olo-dw** [comment]
Maybe some details can be usefull to help you.

**Comment by geerlingguy** [comment]
Yeah... going to close this for now. I would need a lot more details in order to have any chance of helping. What did you do? How are you running this role? What kind of server? Did it ever work at all? Does it work after a reboot? etc.
