### ISSUE TITLE
Support for security other than basic security?

### ISSUE THREAD

**Issue by ringods** [geerlingguy/ansible-role-jenkins#223]
What is the approach in this role to setup Jenkins with something else than basic security? We want to use Google OAuth security realm combined with Role Based authorization.

The `configure default users` handler sets up the Jenkins Internal user database with the `Logged-in users can do anything` authorization strategy.

If you use a pinned Jenkins version and you bump the version, the handler is invoked and any manual security config is reset back to this basic security. Not really what I want.

Another problem with the basic security (sort of) hardcoded is that the admin username and password are used for plugin installation. I'm out of luck now to rerun Ansible on my already deployed Jenkins server to install new or upgrade existing plugins.

What changes do you think would be needed to support this in this role?

**Comment by geerlingguy** [comment]
I generally either set up a different security strategy using a Groovy script or by manually doing it in the UI once the server is up and running.
