### ISSUE TITLE
Non-Default port causes stalling on the *Wait for Jenkins to start up before proceeding* task

### ISSUE THREAD

**Issue by DusanDimitric** [geerlingguy/ansible-role-jenkins#225]
Hi there, first of all thanks for all the Ansible work you've done so far.

## Issue

I get stuck on the following task:

```
TASK [geerlingguy.jenkins : Wait for Jenkins to start up before proceeding.] ********************************************************************************************************************
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (60 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (59 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (58 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (57 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (56 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (55 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (54 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (53 retries left).
....
```
... which just times out eventually. This only happens when I set a non-default port:

```
  roles:
    - geerlingguy.java
    - role: geerlingguy.jenkins
      jenkins_http_port: 80
```

Any help is appreciated,
Thanks!

**Comment by nickbroon** [comment]
This is because jenkins is running as an unprivileged user, so on most systems only has access to ports > 1024.

**Comment by geerlingguy** [comment]
Yeah it's typically best practice to run Jenkins on a higher port. If you want to access it via 80 or 443, you can proxy requests using Nginx or some other load balancer/proxy software (I've also seen HAProxy and Varnish used for this purpose). A side benefit is that you are also then able to do SSL easily and terminate it in the proxying layer (it's a lot easier to integrate Let's Encrypt with Nginx or Apache than Jenkins/Java!).

**Comment by DusanDimitric** [comment]
Thanks guys, appreciate it !
