### ISSUE TITLE
Plugin Blue Ocean fails to install but... it actually gets installed.

### ISSUE THREAD

**Issue by lgg42** [geerlingguy/ansible-role-jenkins#226]
Hello, thanks for this great role.
Today I found that while installing the bluocean plugin the task fails, BUT, if I remove the plugin from the vars and rerun the play, or just run again the play (this time ending OK) the plugin is installed correctly.
The point is that even if the task returns a failed state it actually does get installed.

```
TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ***********
Thursday 28 June 2018  15:48:53 +0000 (0:00:00.381)       0:04:38.765 *********
changed: [10.0.5.73] => (item=kubernetes-cd)
failed: [10.0.5.73] (item=blueocean) => {"changed": false, "details": "Connection failure: timed out", "item": "blueocean", "msg": "Cannot install plugin."}
```

Running Ansible 2.5.5, what other info should I provide?

**Comment by ebartz** [comment]
Same here. It actually tells me that it fails installing all of the defined plugins. When I check Jenkins they are installed without showing any issues.
