### ISSUE TITLE
Allow configuration of Jenkins ports (HTTP/HTTPS)

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-jenkins#23]
See CLI options for startup: https://wiki.jenkins-ci.org/display/JENKINS/Starting+and+Accessing+Jenkins

**Comment by geerlingguy** [comment]
Unfortunately this is nowhere near as simple as a slightly-more-obscure parameter like `--prefix` (see #22 ), because different OS defaults files have different configuration names and default sets. For example, Ubuntu's config file has the `--httpPort` set inside `JENKINS_ARGS`, whereas CentOS's has an empty `JENKINS_ARGS`.

Then the default port variable in the config file is `HTTP_PORT` on Ubuntu and `JENKINS_PORT` in CentOS.

Ugh.

**Comment by geerlingguy** [comment]
In most cases, I just use firewall rules to map ports the way I want, and just stick with the defaults... but I'd rather configure the default ports as part of this role. One option is to create a config file that's included with the role that works cross-platform and has templated vars.

**Comment by dpursehouse** [comment]
I have a fix for this.  Will send a PR when I've got approval to do so (I did it at work and need to follow an open sourcing process).
