### ISSUE TITLE
Incorrect java version in Ubuntu 18.04 Bionic

### ISSUE THREAD

**Issue by supermafete** [geerlingguy/ansible-role-jenkins#240]
Hi,

I tried the role to install jenkins on Ubuntu 18.04. The post-install scripts fails:

> Setting up jenkins (2.146) ...
Job for jenkins.service failed because the control process exited with error code.
See "systemctl status jenkins.service" and "journalctl -xe" for details.
invoke-rc.d: initscript jenkins, action "start" failed.
● jenkins.service - LSB: Start Jenkins at boot time
   Loaded: loaded (/etc/init.d/jenkins; generated)
   Active: failed (Result: exit-code) since Thu 2018-10-11 23:10:35 PDT; 33ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 11475 ExecStart=/etc/init.d/jenkins start (code=exited, status=1/FAILURE)
Oct 11 23:10:35 ubuntu1804.localdomain systemd[1]: Starting LSB: Start Jenkins at boot time...
Oct 11 23:10:35 ubuntu1804.localdomain jenkins[11475]: Found an incorrect Java version
Oct 11 23:10:35 ubuntu1804.localdomain jenkins[11475]: Java version found:
Oct 11 23:10:35 ubuntu1804.localdomain jenkins[11475]: openjdk version "10.0.2" 2018-07-17
Oct 11 23:10:35 ubuntu1804.localdomain jenkins[11475]: OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
Oct 11 23:10:35 ubuntu1804.localdomain jenkins[11475]: OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)
Oct 11 23:10:35 ubuntu1804.localdomain jenkins[11475]: Aborting
Oct 11 23:10:35 ubuntu1804.localdomain systemd[1]: jenkins.service: Control process exited, code=exited status=1
Oct 11 23:10:35 ubuntu1804.localdomain systemd[1]: jenkins.service: Failed with result 'exit-code'.
Oct 11 23:10:35 ubuntu1804.localdomain systemd[1]: Failed to start LSB: Start Jenkins at boot time.
dpkg: error processing package jenkins (--configure):
 installed jenkins package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 jenkins
E: Sub-process /usr/bin/dpkg returned an error code (1)

Best.

**Comment by geerlingguy** [comment]
It looks like you're somehow running Java 10?

This playbook purposely locks in Java 8 for best compatibility—see the playbook that sets up Java 8 across all the different tested platforms here: https://github.com/geerlingguy/ansible-role-jenkins/blob/master/molecule/default/java-8.yml

I'm not sure if Jenkins supports Java 10 yet.

**Comment by supermafete** [comment]
Yes, I forced openjdk8-jdk installation before and then worked well, but the role is supposed to work in bionic (at least, this is that the doc is saying), and bionic has version 10 as default JDK.

I saw that the role is checking java installation. Maybe version 8 can be forced.

**Comment by leos** [comment]
I'm having the same problem. Using Vagrant, starting with a `generic/ubuntu1804` VM and installing using the following playbook:
```
- hosts: jenkins
  roles:
  - role: geerlingguy.java
    become: yes
    java_packages:
      - openjdk-8-jdk
  - role: geerlingguy.jenkins
    become: yes
```
It dies in the same place as the OP and ssh'ing into the VM confirms that it's using Java 10 instead of Java 8. Is it possible that the locking mechanism isn't working properly on the latest 18.04? or am I doing something wrong in the playbook?

**Comment by davelosert** [comment]
I am having the same problem using AWS with a fresh Ubuntu 18.04. installation.

Jenkins defaults to openjdk-11-jdk
```
TASK [geerlingguy.java : Ensure Java is installed.] *****************************************************************************************
changed: [ec_jenkins_master] => (item=[u'openjdk-11-jdk'])
```
Maybe because it is set as the default JDK within update-alternatives?

```
$ update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
```

**Comment by davelosert** [comment]
Nevermind my comment above... the openjdk-8 was just there because i forcefully installed it before.

Running the naked jenkins-role on a fresh Ubuntu 18.04., it definitly installs openjdk-11-jdk.

Running the installation in verbose mode i saw that the **java_package** is not being set - therefore the java-role uses the default version defined in the java-role here: https://github.com/geerlingguy/ansible-role-java/blob/master/vars/Ubuntu-18.yml

However, If I forcefully set the **java_package** variable like this within my playbook it works:

```
    - role: geerlingguy.jenkins
       java_packages:
        - openjdk-8-jd
```
Maybe this helps in resolving the issue?

**Comment by mzaian** [comment]
I checked here https://jenkins.io/doc/administration/requirements/java/ 

Java 8 is the ONLY supported runtime environment, both 32-bit and 64-bit versions are supported

So this should be changed to "openjdk-8-jdk" in https://github.com/geerlingguy/ansible-role-java/blob/master/vars/Ubuntu-18.yml
@geerlingguy what do you think?

**Comment by geerlingguy** [comment]
@mzaian - The `geerlingguy.java` role is used by thousands of different projects, not just this Jenkins role; the defaults are typically the recommended default versions for the OS/distro, and those should not be changed.

Users of this role should configure their particular server to have the proper Java version for the version of Jenkins they run—see, for example, how this role's tests build it's local environments correctly: 

https://github.com/geerlingguy/ansible-role-jenkins/blob/master/molecule/default/java-8.yml#L39-L44

So, I will not change the default in the upstream/generic Java role, but I recommend no matter what OS/distro you use, you install Java (whether using my java role or some other method of installation) at a version that's supported by the latest version of Jenkins.

Again, if you have this issue, please see https://github.com/geerlingguy/ansible-role-jenkins/blob/master/molecule/default/java-8.yml#L39-L44 for how it's fixed for Ubuntu 18.04; and see the rest of the file for how to resolve it on other OS versions and distros.

**Comment by m-j** [comment]
So is there any consensus how this role should be used with 18.04? I run something like this but it fails:

`- hosts: ci_master
  become: true
  roles:
    - role: geerlingguy.java
      vars:
      java_packages:
        - openjdk-8-jdk  

    - role: geerlingguy.jenkins
      java_packages:
        - openjdk-8-jdk    
      vars:
        jenkins_package_state: present
        jenkins_plugins: ['configuration-as-code', 'git', 'git-client', 'workflow-aggregator']`

**Comment by CloudSurgeon** [comment]
Your post is very vague. What failure message do you get? These playbooks work fine with 18.04:
https://github.com/geerlingguy/ansible-role-jenkins/tree/master/molecule/default

**Comment by m-j** [comment]
I was getting startup error regarding java fersion. However after following your link I've made it work:

```

- hosts: ci_master
  become: true
  pre_tasks:
    - name: Set the java_packages variable (Ubuntu).
      set_fact:
        java_packages:
          - openjdk-8-jdk
    - name: update cache
      apt:
        update_cache: true
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
      vars:
        jenkins_package_state: present

```

Thanks!

**Comment by geerlingguy** [comment]
Yeah, Java / JDK in Ubuntu 18.04 has been a pretty weird situation; they have a version 11 package which used to install 8 I think, then it installed 10, and they plan on updating the same package to install 11. Something like that.

So yeah, using this workaround is the only way I've found to make Java installations on 18.04 work with current Jenkins.
