### ISSUE TITLE
Fetching update-center.json tends to time out

### ISSUE THREAD

**Issue by tazle** [geerlingguy/ansible-role-jenkins#241]
Recently fetching update-center.json has been very flaky for us. The timeout is currently the default (10 seconds). Bumping this up to 30 seconds seems to solve the issue for us.

**Comment by tazle** [comment]
Why does merging a PR to my fork close the issue in the parent? Crazy GitHub...

**Comment by geerlingguy** [comment]
This is fixed via https://github.com/geerlingguy/ansible-role-jenkins/pull/252
