### ISSUE TITLE
How could you create an initial jenkins job?

### ISSUE THREAD

**Issue by jakelacey2012** [geerlingguy/ansible-role-jenkins#243]
Lets say when I deploy my Jenkins server I want it to have some default jobs, how do I do that with this role? Would it be part of `jenkins_init_changes` config?

**Comment by geerlingguy** [comment]
@jakelacey2012 - I typically bundle up the jobs either as templates or raw config.xml file with a custom role for each jenkins server, and then manage the jobs that way—when I update a job, I pull the `config.xml` from the Jenkins home jobs dir and update it in the playbook. Then every time I run the playbook, it copies or templates up all the jobs again to keep them in the same state.

**Comment by ehime** [comment]
Interesting.. this breaks for me @geerlingguy using https://github.com/ehime/terraform-jenkins/blob/v1.0.2/ansible/jenkins.yml#L55-L60

basic job is being sourced (hello world node thing), errs out with...

```bash
<34.229.78.81> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="~/terraform-jenkins/_keys/GEHC-032"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=~/.ansible/cp/e551878248 34.229.78.81 '/bin/sh -c '"'"'rm -f -r /home/ec2-user/.ansible/tmp/ansible-tmp-1540921523.71-219391270607234/ > /dev/null 2>&1 && sleep 0'"'"''
<34.229.78.81> (0, '', 'OpenSSH_7.6p1, LibreSSL 2.6.2\r\ndebug1: Reading configuration data ~/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 48529\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_sanLTc/ansible_module_jenkins_job.py", line 300, in create_job
    self.server.create_job(self.name, config_file)
  File "/usr/lib/python2.7/site-packages/jenkins/__init__.py", line 991, in create_job
    config_xml.encode('utf-8'), DEFAULT_HEADERS))
  File "/usr/lib/python2.7/site-packages/jenkins/__init__.py", line 447, in jenkins_open
    e.code, e.msg)
JenkinsException: Error in request. Possibly authentication failed [500]: Server Error

fatal: [34.229.78.81]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": "<?xml version='1.0' encoding='UTF-8'?>\n<flow-definition plugin=\"workflow-job@2.10\">\n  <actions/>\n  <description></description>\n  <keepDependencies>false</keepDependencies>\n  <properties>\n    <org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>\n      <triggers/>\n    </org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>\n  </properties>\n  <definition class=\"org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition\" plugin=\"workflow-cps@2.30\">\n    <script>\n      node { echo &apos;Hello World&apos; }\n    </script>\n    <sandbox>true</sandbox>\n  </definition>\n  <triggers/>\n</flow-definition>",
            "enabled": null,
            "name": "test-auto",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "token": null,
            "url": "http://localhost:8080",
            "user": "admin"
        }
    },
    "msg": "Unable to create job, Error in request. Possibly authentication failed [500]: Server Error for http://localhost:8080"
}
	to retry, use: --limit @~/terraform-jenkins/ansible/jenkins.retry

PLAY RECAP *********************************************************************************************************************************************
34.229.78.81               : ok=46   changed=20   unreachable=0    failed=1

make: *** [provision] Error 2
```

verified that U/P works by logging into the console etc as well, maybe the url? Not sure...

**Comment by jakelacey2012** [comment]
>@jakelacey2012 - I typically bundle up the jobs either as templates or raw config.xml file with a custom role for each jenkins server, and then manage the jobs that way—when I update a job, I pull the config.xml from the Jenkins home jobs dir and update it in the playbook. Then every time I run the playbook, it copies or templates up all the jobs again to keep them in the same state.

I'm new to a lot of this so I don't really understand much do you have an example I could look at ?

**Comment by geerlingguy** [comment]
Here's one full build example: https://github.com/geerlingguy/drupal-jenkins-multisite

Note that even users of that example are also asking for a better way to manage Jenkins jobs. If you use Pipelines and have jobs integrated with a `Jenkinsfile` in your app repos, that's one way of doing it easily... but if you use traditional Jenkins jobs it's a bit more annoying.

See also: https://github.com/geerlingguy/drupal-jenkins-multisite/issues/7

**Comment by jakelacey2012** [comment]
okay I'll take a look thanks, yeah I'm thinking of using pipelines with Jenkinsfiles. Effectively what I'm trying to do is get as much in source control as possible. The only thing I really want in my backups is some recent job history.

I may have more questions about how that repo is structured because I have no idea xD - But will have a dig and see what I can find. Thanks.

**Comment by fubarhouse** [comment]
@jakelacey2012,

Another option is to basically stash your jenkins profile directory into a directory and use a docker container to mount it into running it on a jenkins process. I've been looking at shifting my old jenkins stuff into a docker-compose job inside of docker-compose.

It's incredibly predictable, maintainable and sustainable.

It also does away with all the fluff, but the repository would need to be kept private.

**Comment by geerlingguy** [comment]
FWIW, I'm using the `jenkins/jenkins:slim` Docker container as my base for some Kubernetes Docker installs now, and I basically mount the `$JENKINS_HOME` directory as a persistent volume. Then I take backups of that PV, which contains all the Jenkins jobs in the `jobs` directory.

The traditional way of managing Jenkins backup/recovery is to backup the entire `$JENKINS_HOME` and restore it as needed.

Taking it a step further, to ensure jobs are all in source control, you can pull them back into your repo and have either Ansible or some other mechanism copy them over the live `config.xml` files, then restart Jenkins or hit the 'Reload config from disk' button in Jenkins' admin to refresh the jobs from the updated values.

**Comment by dx-pbuckley** [comment]
In the past I’ve used Jenkins job builder (JJB) to keep jenkins jobs in source control. Long before jenkinsfiles existed it’s been fantastic at keeping jobs and templates centrally controlled. And the job defs are stored as yaml instead of xml. The best part is that JJB uses the Jenkins rest api to update jobs, so no need to restart Jenkins.

**Comment by jakelacey2012** [comment]
Ahh cool, @dx-pbuckley I guess I could use JJB to point at a `Jenkinsfile` on a repo. But don't know if thats a silly thing to do.
