### ISSUE TITLE
Jenkins installation fails when /tmp is set to "noexec"

### ISSUE THREAD

**Issue by proffalken** [geerlingguy/ansible-role-jenkins#264]
In order to provide a secure plaform, all our centos servers have `/tmp` set with `noexec` privileges.

This causes Jenkins to stop working by default as it requires the ability to load/execute files in the temporary directory (see https://support.cloudbees.com/hc/en-us/articles/215281717-Jenkins-fails-to-start-with-JNA-error for more on that).

If the Jenkins tmp directory was able to be specified as a variable, then this role could be deployed without issue into platforms that are CIS compliant.

**Comment by CloudSurgeon** [comment]
You should just need to override` jenkins_java_options` in your playbook like so:

jenkins_java_options: '-Djenkins.install.runSetupWizard=false -Djava.io.tmpdir=$JENKINS_HOME/tmp'

**Comment by proffalken** [comment]
Yeah, I tried that, but that means that you have to create the jenkins user as a "pretask" as well, otherwise you can't securely assign the new temp dir to the correct user, because that user doesn't exist until after the role has run.

At the moment, I've set `-Djava.io.tmpdir=/var/lib/jenkins/` and that works, but it's not ideal.

I do intend to file a PR for this, I just wanted a place holder issue for it as I don't know when I'll have the time to do that.
