### ISSUE TITLE
Master-Slave Setup

### ISSUE THREAD

**Issue by rohinrohin** [geerlingguy/ansible-role-jenkins#266]
Is it possible to use this role to bring up master and slave nodes? 
If so, can you point me to some documentation?

Thank you -Rohin

**Comment by geerlingguy** [comment]
Right now this role does not do anything in particular to help with Jenkins slave setup (just the master part). There are a few other roles on Galaxy which may help with the slave connection, e.g. https://galaxy.ansible.com/ChristopherDavenport/jenkins-slave and https://galaxy.ansible.com/lean_delivery/jenkins_slave
