### ISSUE TITLE
Jenkins plugins install fails

### ISSUE THREAD

**Issue by cjohannsen81** [geerlingguy/ansible-role-jenkins#269]
Hi, maybe something has changed in the last days but my script isn't working any longer. The plugin install fails with:

TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ***********
FAILED - RETRYING: Install Jenkins plugins using password. (3 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (2 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (1 retries left).
failed: [35.153.204.135] (item=git) => {"attempts": 3, "changed": false, "details": "HTTP Error 403: No valid crumb was included in the request", "item": "git", "msg": "Cannot install plugin."}
FAILED - RETRYING: Install Jenkins plugins using password. (3 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (2 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (1 retries left).
failed: [35.153.204.135] (item=sonar) => {"attempts": 3, "changed": false, "details": "HTTP Error 403: No valid crumb was included in the request", "item": "sonar", "msg": "Cannot install plugin."}
FAILED - RETRYING: Install Jenkins plugins using password. (3 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (2 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (1 retries left).
failed: [35.153.204.135] (item=ssh) => {"attempts": 3, "changed": false, "details": "HTTP Error 403: No valid crumb was included in the request", "item": "ssh", "msg": "Cannot install plugin."}
FAILED - RETRYING: Install Jenkins plugins using password. (3 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (2 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (1 retries left).
failed: [35.153.204.135] (item=ssh-slaves) => {"attempts": 3, "changed": false, "details": "HTTP Error 403: No valid crumb was included in the request", "item": "ssh-slaves", "msg": "Cannot install plugin."}
FAILED - RETRYING: Install Jenkins plugins using password. (3 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (2 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (1 retries left).
failed: [35.153.204.135] (item=junit) => {"attempts": 3, "changed": false, "details": "HTTP Error 403: No valid crumb was included in the request", "item": "junit", "msg": "Cannot install plugin."}
FAILED - RETRYING: Install Jenkins plugins using password. (3 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (2 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (1 retries left).
failed: [35.153.204.135] (item=mattermost) => {"attempts": 3, "changed": false, "details": "HTTP Error 403: No valid crumb was included in the request", "item": "mattermost", "msg": "Cannot install plugin."

I deactivated the CORS Security in the Jenkins config but still no luck.

**Comment by dreich-nucleus** [comment]
I saw the same thing yesterday. The [Jenkins 2.192 release](https://jenkins.io/changelog/) (2019-08-28) does talk about some security related changes, including CSRF changes. The Error above seems to be related to CSRF when it occurs in other contexts, so this might be it. I'm going to try installing an older Jenkins to see if the error still occurs.

**Comment by dreich-nucleus** [comment]
Yep. 2.191 seems to be working.

**Comment by sashokbg** [comment]
Having the same issue, I tried enabling the "Compatibility mode for proxies" as described in the issue below, but unfortunately the issue persists.

https://github.com/spinnaker/spinnaker/issues/2067

The solution as mentioned by @dreich-nucleus using 2.191 fixed the problem.

```
  vars:
    jenkins_version: "2.191"
```

**Comment by dizeee** [comment]
Same issue with Jenkins `2.190.1`.

**Comment by muellert** [comment]
I tried to run this role against a pre-installed Jenkins and then noted that the problem existed even after upgrading to 2.204, which sort of worked on a different host. Can it be that this role generally does not work if the target host is localhost?

**Comment by muellert** [comment]
I just made another attempt, purging Jenkins, but I keep getting:

```
FAILED - RETRYING: Install Jenkins plugins using password. (1 retries left).Result was: {
    "attempts": 3,
    "changed": false,
    "details": "HTTP Error 401: Unauthorized",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": true,
            "group": "jenkins",
            "http_agent": "ansible-httpget",
            "jenkins_home": "/var/lib/jenkins",
            "mode": "0644",
            "name": "gitea",
            "owner": "jenkins",
            "params": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "timeout": 30.0,
            "unsafe_writes": null,
            "updates_expiration": 86400,
            "updates_url": "https://updates.jenkins.io",
            "url": "http://localhost:8080",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "admin",
            "use_proxy": true,
            "validate_certs": true,
            "version": null,
            "with_dependencies": true
        }
    },
    "msg": "Cannot get CSRF",
    "retries": 4
}

**Comment by jkugler** [comment]
> "msg": "Cannot get CSRF"

This is the problem right here. Jenkins now implements CSRF prevention, so to install plugins, the Ansible module will actually have to script logging in to the Jenkins instance, then run the commands needed to install the plugin(s).

**Comment by muellert** [comment]
On Sun, Dec 01, 2019 at 02:12:42PM -0800, Joshua Kugler wrote:
> > "msg": "Cannot get CSRF"
> 
> This is the problem right here. Jenkins now implements CSRF
> prevention, so to install plugins, the Ansible module will actually
> have to script logging in to the Jenkins instance, then run the
> commands needed to install the plugin(s).

I know. I've spent some time now to look into getting this token, but
the url lookup or the get_uri modules are not yet very helpful.

FWIW, there's an entry in the Jenkins wiki about it:

https://wiki.jenkins.io/display/JENKINS/Remote+access+API

**Comment by jkugler** [comment]
Right now you use:
```
url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
```
According to https://wiki.jenkins.io/display/JENKINS/Remote+access+API wouldn't that just be a request to
```
{{ url }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)
```
And use the token returned? Just taking that from the "CSRF Protection" section on that page.  Then:
> This will print something like "Jenkins-Crumb:1234abcd", which you should add to the subsequent request.

Are you saying `get_uri` doesn't return the information in a good form? Maybe depend on `curl` (don't know if that's possible) and register the stdout and use that? Not sure if the uri module would help here either. Doesn't sound like it returns the contents of the request. But, it shows an example that uses a return value that isn't documented. Or maybe it's a header?
```
- name: Login to a form based webpage, then use the returned cookie to access the app in later tasks
  uri:
    url: https://your.form.based.auth.example.com/index.php
    method: POST
    body_format: form-urlencoded
    body:
      name: your_username
      password: your_password
      enter: Sign in
    status_code: 302
  register: login

- name: Connect to website using a previously stored cookie
  uri:
    url: https://your.form.based.auth.example.com/dashboard.php
    method: GET
    return_content: yes
    headers:
      Cookie: "{{ login.set_cookie }}"
```
Hmm:
> return_content
> Whether or not to return the body of the response as a "content" key in the dictionary result.
Independently of this option, if the reported Content-type is "application/json", then the JSON is always loaded into a key called json in the dictionary results.

Maybe?

**Comment by muellert** [comment]
Hi Joshua,

On Sun, Dec 01, 2019 at 10:46:04PM -0800, Joshua Kugler wrote:
> {{ url }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)

I tried to use the built-in tools and avoid the curl call so far. But it
is not obvious to me how to stick all the parameters into eg. the 'uri'
lookup call.

But if I'm going to lose patience, I'll definitely try that route
instead.

Thank you!

**Comment by CloudSurgeon** [comment]
I don't know if this will help you, but I just pulled this out of some old
Jenkins scripting I had created a few years back that will fetch the crumb
and use it in later jobs. The USER_API_TOKEN was stored in a .passwd file
that I sourced into the script:

URL="http://buildserver:8080"

CONTENT_TYPE="Content-Type: application/xml"

FOLDER_XML=JOB_FOLDER.xml

JENKINS_CRUMB=$(curl "$URL
/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,%22:%22,//crumb)"
--user ${USER_API_TOKEN})

cat ${FOLDER_XML} | curl -X POST "$URL/createItem?name=${ROOT_FOLDER}"
--header "${CONTENT_TYPE}" --header "${JENKINS_CRUMB}" --user
${USER_API_TOKEN} -d @-

**Comment by markhepburn** [comment]
I hit this too, but it seems to be fixed in Ansible itself: https://github.com/ansible/ansible/issues/61672

I haven't verified from what version it has been included, but I had the problem with 2.8.3, and upgrading to the latest, 2.9.6, seems to have fixed it.

**Comment by leonardocastanodiaz** [comment]
I am facing the same issue and the latest version that works is 
`jenkins_version: "2.191"`

Anything different than that I got the same error ...

**Comment by leonardocastanodiaz** [comment]
amazon-ebs: TASK [geerlingguy.jenkins : Install our specific version of Jenkins.] **********
    amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "msg": "dpkg --force-confdef --force-confold -i **/tmp/jenkins_2.192_all.deb failed"**, "stderr": "Job for jenkins.service failed because the control process exited with error code.\nSee \"systemctl status jenkins.service\" and \"journalctl -xe\" for details.\ninvoke-rc.d: initscript jenkins, action \"start\" failed.\ndpkg: error processing package jenkins (--install):\n installed jenkins package post-installation script subprocess returned error exit status 1\nErrors were encountered while processing:\n jenkins\n", "stderr_lines": ["Job for jenkins.service failed because the control process exited with error code.", "See \"systemctl status jenkins.service\" and \"journalctl -xe\" for details.", "invoke-rc.d: initscript jenkins, action \"start\" failed.", "dpkg: error processing package jenkins (--install):", " installed jenkins package post-install

**Comment by boldandbusted** [comment]
Just FYI, I'm suddenly seeing this issue after this role installed plugins fine. Now, the role reports that plugins are installed, but none are, AND, for some reason, Jenkins displays zero plugins under "Available" under "Manage Plugins". :( My guess is that there's something else inside the LTS version of Jenkins I'm installing that is silently blocking functioning plugins. Note that this is in a Vagrant-based context, so a fresh Jenkins, with nothing changed in the code.

**Comment by rgarrigue** [comment]
I'm hitting the issue on a shorter loop : I've a couple hours old instance where I'm running Ansible again and again to come up with the proper CASC configuration. At some point I just hit the error

```
...
FAILED - RETRYING: Install Jenkins plugins using password. (3 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (2 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (1 retries left).
failed: [i-09a6946693ef4fe79] (item=view-job-filters) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "details": "HTTP Error 401: Unauthorized", "item": "view-job-filters", "msg": "Cannot get CSRF"}
```

Jenkins documentation about CSRF https://www.jenkins.io/doc/book/security/csrf-protection/ mention a wait to disable it entirely

> To disable CSRF protection, set the system property hudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION to true on startup
