### ISSUE TITLE
How to handle backup / restore and multi-master node setups

### ISSUE THREAD

**Issue by CodingSpiderFox** [geerlingguy/ansible-role-jenkins#272]
Please be patient with me as I'm completely new to ansible.

I'm planning a proposal for a new development infrastructure.
Does this role allow multi-master ("failover") setups?

How can I backup the master's data and restore it using this role in case everything breaks?

I appreciate your contributions :)

**Comment by geerlingguy** [comment]
This role does not currently support the management of multi-master setups with Jenkins. For backups, I tend to backup the entire `$JENKINS_HOME` directory (whether to S3, an NFS server, or wherever else you normally store backups).

I tend to use my [geerlingguy.backup](https://github.com/geerlingguy/ansible-role-backup) role for simpler backup scenarios where I'm just dumping the folder off to a backup server.
