### ISSUE TITLE
 ordinal not in range(128) error when setting plugin state from present to latest

### ISSUE THREAD

**Issue by B-Lukas** [geerlingguy/ansible-role-jenkins#287]
Hi, I tried to set the `jenkins_plugins_state` from `present` to `latest`, sadly I get This Error Message during the `TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ` task:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3958: ordinal not in range(128)
failed: [ci] (item=configuration-as-code) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": "configuration-as-code", "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_jenkins_plugin_payload_6ow7a6ar/ansible_jenkins_plugin_payload.zip/ansible/modules/web_infrastructure/jenkins_plugin.py\", line 791, in <module>\n  File \"/tmp/ansible_jenkins_plugin_payload_6ow7a6ar/ansible_jenkins_plugin_payload.zip/ansible/modules/web_infrastructure/jenkins_plugin.py\", line 774, in main\n  File \"/tmp/ansible_jenkins_plugin_payload_6ow7a6ar/ansible_jenkins_plugin_payload.zip/ansible/modules/web_infrastructure/jenkins_plugin.py\", line 489, in install\n  File \"/tmp/ansible_jenkins_plugin_payload_6ow7a6ar/ansible_jenkins_plugin_payload.zip/ansible/modules/web_infrastructure/jenkins_plugin.py\", line 575, in _download_updates\n  File \"/usr/lib/python3.6/encodings/ascii.py\", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3958: ordinal not in range(128)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

I am kind of lost here.

**Comment by petk** [comment]
Hello, I believe the issue is related to this https://github.com/ansible/ansible/pull/55253/files and once you patch manually the `jenkins_plugin.py` file on system it passes you through and works ok.
