### ISSUE TITLE
Cant change to port 80?

### ISSUE THREAD

**Issue by thepenguinthatwants** [geerlingguy/ansible-role-jenkins#292]
It  doesnt seem to run if I change port from 8080 to 80
`jenkins_http_port: 80`

TASK [jenkins : Wait for Jenkins to start up before proceeding.] ******************************************************************************************************************************************************************************
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (60 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (59 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (58 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (57 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (56 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (55 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (54 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (53 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (52 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (51 retries left).
FAILED - RETRYING: Wait for Jenkins to start up before proceeding. (50 retries left).

**Comment by thepenguinthatwants** [comment]
After seeing issue issues/225 I understand a bit more.
But whats the difference for running it on a priviledged user?
Also I am using virtual enviroment so wondering if there are any easy method to change it to port 80?

**Comment by slikk66** [comment]
im having same issue

**Comment by spommerening** [comment]
I had the same issue and solved it by using iptables:

`iptables -t nat -A PREROUTING -i en+ -p tcp --dport 80 -j REDIRECT --to-port 8080`

IMHO easiest way to solve this. Another method would be using `pound` with `certbot` integration. 
This would make sense if you plan to use SSL certificates anyway (or use Nginx if preferred).
My current Jenkins is only accessible using a VPN so no certificates are necessary anyway. ;-) 

Hope this helps.
