### ISSUE TITLE
integrate with configuration-as-code plugin

### ISSUE THREAD

**Issue by timblaktu** [geerlingguy/ansible-role-jenkins#300]
I'm working on provisioning some new Jenkins masters, and the initial approach I'm taking is to use this role to install jenkins, and to specify for it to install the configuration-as-code plugin, relying on the latter for the lion's share of Jenkins configuration. It appeared that this would be as simple as prepending a task to my jenkins playbook to copy my `jenkins.yml` file, and my job-dsl groovy files onto the server. What I have found is that this approach works when the universe is perfectly aligned, but most of the time, there are significant problems with this workflow:

* [JCasC cannot install plugins](https://github.com/jenkinsci/configuration-as-code-plugin#installing-plugins), so we do it with `jenkins_plugins`. 
* If you include configuration-as-code in the list, and your CasC yaml file(s) do not have the perfect content, which is nearly impossible to do during development, Jenkins will crash on startup.
* Since Jenkins has crashed, subsequent runs of this role will timeout on "Wait for Jenkins to start up before proceeding", and the role will not be able to install the plugins specified.
* Since JCasC yaml specifies configuration for plugins as well as global configuration items, having the "perfect content" means that the `jenkins.yaml` file only attempts to configure plugins that have been installed.

This means that to properly support using JCasC plugin, this role might need to be modified to install plugins by manually copying the downloaded plugins files to the ‘JENKINS_HOME/plugins’ folder _before restarting Jenkins and waiting for it_. This won't prevent Jenkins from crashing due to JCasC problems, but _it will greatly reduce such errors caused by mismatches between `jenkins_plugins` role variable and JCasC's `jenkins.yaml`_.

I can see that this role is just using `jenkins_plugin` ansible module to install each plugin. I haven't yet looked at the code to see how this module works. Perhaps it is already working this way..

Implicit in this, I wanted to find out if there was any plan yet to integrate JCasC into this role, since:

1. They overlap in significant ways, and 
2. The [Jenkins Enhancement Proposal](https://github.com/jenkinsci/jep/tree/master/jep/201) that [the JCasC team submitted](https://github.com/jenkinsci/configuration-as-code-plugin#jenkins-enhancement-proposal) has been approved, so *JCasC functionality will be integrated into Jenkins core*.

I just thought it might be a good thing to get a head start on this and to promote JCasC usage through this role, which I know is very popular. I'm happy to fork, modify, test and submit a PR for this change if someone can provide feedback on any prior work/thought and point me in the right direction. I'm familiar with ansible, but am just starting to use JCasC. 

Thanks for your time and consideration.

**Comment by ZakHargz** [comment]
This would be another nice one to have, you could add a `include_tasks` within main.yml to do something like this:

`- name: include vars
     include_vars:
        file: config_as_code.yml

- name: Adding jenkins config as code
     template:
        src: jenkins_config_as_code.yaml.j2
        dest: '{{ jenkins_home }}/jenkins.yaml'
        owner: jenkins
        group: jenkins
        mode: 0640
     notify: 
       - Restart jenkins
`

 jenkins_config_as_code.yaml.j2:

`{{ creds_list }}`

config_as_code.yml:

`
creds_list: |
  credentials:
    system:
      domainCredentials:
        - credentials:
           - basicSSHUserPrivateKey:
               id: "SSH_CRED_ID"
               privateKeySource:
                 directEntry:
                   privateKey: "----PRIVATE KEY CONTENT----"
               scope: GLOBAL
               username: "---USERNAME---"
`

Well, something along those lines :D

**Comment by timblaktu** [comment]
@ZakHargz I'm doing these things in my containing playbook, before invoking this role. I finally got everything hacked together and working, but it's quite a franken-project. I'm also using wcm_devops meta roles to tie some things together. When I end up making some time to clean up this Jenkins Ansible project, looks like there's a good opportunity to add this and perhaps some of the other features to this role. Let me know if you have other requests or experience with using this role with JCasC. Cheers.

**Comment by B-Lukas** [comment]
I'm also doing this and noticed that this is quite unstable. I'm always using the latest Jenkins LTS and sometimes, when I do a Ansible run, Jenkins will Update or only some Plugins. In my case he didn't update the Git Plugin, which broke some dependencies, which then made Jenkins unable to load all Plugins, which then made it unable for JCasC to Configure Plugins which are not loaded. This then results in an error on Jenkins startup, which can only be resolved by editing the jenkins_config_as_code.yaml on the Server, removing the not loaded plugins, restarting jenkins, updating the Plugins and finally Ansible can run again
