### ISSUE TITLE
What is Best Practice for Uninstalling (or making other state changes to) Plugins with this Role?

### ISSUE THREAD

**Issue by timblaktu** [geerlingguy/ansible-role-jenkins#302]
Looking at the code, I see that for each of the specified `jenkins_plugins`, `jenkins_plugins_state` role variable passes through directly to the `jenkins_plugin` ansible module (unless a version is specified, in which case it is hard coded to "present"). Does this mean that if I want to use this role to remove one or more plugins that I need to invoke this role another time with  `jenkins_plugins` set to the plugins I want to remove, and `jenkins_plugins_state=absent`?

I suppose what I'd like to see is for `jenkins_plugins` entries to support a `state` element for each plugin, and to add support to the "Install Jenkins Plugins" task in  `tasks/plugins.yml` to pass this to `jenkins_plugin` ansible module, like this:

```
- name: Install Jenkins plugins using password.
  jenkins_plugin:
    .
    .
    .
    state: "{{ 'present' if item.version is defined else item.state if item.state is defined else jenkins_plugins_state }}"
    .
    .
    .
  with_items: "{{ jenkins_plugins }}"
    .
    .
    .
```

**Comment by russellvt** [comment]
Might be a good time to address this, as two common plugins have recently gone EOL (at least, our last "Jenkins update" using this role managed to get these to pop as warnings in the Jenkins UI).

- [Static Analysis Utilities](https://plugins.jenkins.io/analysis-core/)
- [Pipeline: Declarative Agent API](https://plugins.jenkins.io/pipeline-model-declarative-agent/)

**Comment by ZakHargz** [comment]
Sorry to jump onto the back of this, but it would also be nice to have this included. At the moment, when I try and uninstall a plugin, I get the following:

`    failed: [ansible-role-jenkins] (item=git) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "details": "HTTP Error 405: Method Not Allowed", "item": "git", "msg": "Plugin not found. http://localhost:8080/pluginManager/plugin/git/doUninstall"}
`

Here is the block I wrote:

`- name: Running through and uninstalling specified plugins
  jenkins_plugin:
    name: '{{ item.name | default(item) }}'
    url_username: '{{ jenkins_administrator_username }}'
    url_password: '{{ jenkins_administrator_password }}'
    state: absent
  with_items: '{{ jenkins_uninstall_plugins }}'
  when: jenkins_administrator_password | default(false)
  notify: Restart Jenkins service
  register: plugin_uninstall_result
  until: plugin_uninstall_result is success`
