### ISSUE TITLE
'Install Jenkins plugins using password' - DOES NOT WORKS!!

### ISSUE THREAD

**Issue by Alex-SBK** [geerlingguy/ansible-role-jenkins#315]
Hello,  geerlingguy!
task 'Install Jenkins plugins using password' in plugins.yml doest not working.

I edited the lines in the main file:
```
# Plugin list can use the plugin name, or a name/version dict.
jenkins_plugins: #[]
  - docker-plugin
#  - name: influxdb
#    version: "1.12.1"
```

but then Ansible shows this error:
```
TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ***********
FAILED - RETRYING: Install Jenkins plugins using password. (3 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (2 retries left).
FAILED - RETRYING: Install Jenkins plugins using password. (1 retries left).
**failed: [app1] (item=docker-plugin) => {"attempts": 3, "changed": false, "details": "HTTP Error 403: Forbidden", "item": "docker-plugin", "msg": "Cannot install plugin."}**
```

What am I doing wrong? What should I do with this, please help!

**Comment by AngelVazquezArroyo** [comment]
I am experimenting the same issue, with the last version: 4.3.0

**Comment by YanChii** [comment]
Same problem here.

**Comment by benjaoming** [comment]
Running into it, too. It's happening after a playbook has been otherwise successful for the past many days. So I'm not sure what the issue is. We didn't upgrade ansible-role-jenkins.

**Comment by benjaoming** [comment]
I found that my own issue was due to pilot error - https://github.com/geerlingguy/ansible-role-jenkins/issues/269 helped me understand it better.

**Comment by AngelVazquezArroyo** [comment]
@benjaoming I have no more problems, since I have upgraded my Ansible Version to 2.9.6

**Comment by benjaoming** [comment]
My issue seems to be that changing `jenkins_hostname` after having done a first deployment just isn't trivial.

**Comment by dchidelf** [comment]
I just ran into this issue and realized the default version of ansible installed on ubuntu is quite old.
The updated CSRF requirements in newer Jenkins versions isn't supported in older versions of ansible's jenkins_plugin module.
After upgrading my ansible version to 2.9.x this error went away for me.
