### ISSUE TITLE
Suggestion: Add a task to uninstall jenkins

### ISSUE THREAD

**Issue by cmoulliard** [geerlingguy/ansible-role-jenkins#328]
## Suggestion

This project/role installs nicely as a service jenkins and starts it but it dont propose/offer an option to stop/uninstall the service, clean the folders where jenkins has been deployed (/var/lib/jenkins), ...
this is the reason I would like to propose to define a task performing such uninstallation using a boolean `-e remove=true`

WDYT ? 

@geerlingguy

**Comment by geerlingguy** [comment]
@cmoulliard - I don't handle deprovisioning/uninstall in my roles—for my own servers, when I want to get rid of something like Jenkins, I delete the server and build it fresh without the Jenkins role. Alternatively, if I set it up using Docker, I terminate the container and clean up any remaining volumes.
