### ISSUE TITLE
Role defines java_packages variable but does not use it - java_packages are not installed

### ISSUE THREAD

**Issue by m8ram** [geerlingguy/ansible-role-jenkins#337]
The README.md and several default files in the molecule define a `java_packages` variable.

The variable is not used anywhere in the role and as a result no JRE is installed.
And as a result of that Jenkins fails to start.

**Comment by bertvv** [comment]
You can install Java using e.g. `geerlingguy.java`. See the [Example playbook](https://github.com/geerlingguy/ansible-role-jenkins#example-playbook)
