### ISSUE TITLE
Since Jenkins 2.332.1, option jenkins_java_options is no longer working

### ISSUE THREAD

**Issue by nad56** [geerlingguy/ansible-role-jenkins#360]
Hello,

Since Jenkins 2.332.1, Jenkins has moved from system V to systemd and the jenkins_java_options is no longer working.
/etc/sysconfig/jenkins file is now obsolete and new file /etc/systemd/system/jenkins.service.d/override.conf should be provided.

Could you have a look at this?

Thanks a lot!
Nadège

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/ansible-role-jenkins/pull/354
