### ISSUE TITLE
Can / will new Jenkins signing key be added?

### ISSUE THREAD

**Issue by wivory** [geerlingguy/ansible-role-jenkins#378]
I'm seeing a key error 

TASK [geerlingguy.jenkins : Add Jenkins apt repository.] ***********************
fatal: [...]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:GPG error: https://pkg.jenkins.io/debian binary/ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5BA31D57EF5975CA, E:The repository 'https://pkg.jenkins.io/debian binary/ Release' is not signed."}

I'd guess this relates to the new Jenkins signing key as described at https://www.jenkins.io/blog/2023/03/27/repository-signing-keys-changing/

Is there a plan to update this / a known workaround?

**Comment by manelso** [comment]
I've bypassed the error defining the key and repo vars as the playbook is expecting...

`
    jenkins_repo_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
    jenkins_repo_url: "deb [signed-by=/etc/apt/trusted.gpg.d/jenkins.asc] https://pkg.jenkins.io/debian binary/"
`

**Comment by timothylytle** [comment]
> jenkins_repo_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
>   jenkins_repo_url: "deb [signed-by=/etc/apt/trusted.gpg.d/jenkins.asc] https://pkg.jenkins.io/debian binary/"

This worked for me!  Thanks!

**Comment by Starwolf-001** [comment]
I have a similar issue. My jenkins instances at work died. I decided to check if I could fix this up and replicate the issue encountered by running our IaC to set up another instance.

Unfortunately at the [geerlingguy.jenkins : Add Jenkins apt repository key.] task my IaC failed for key_id: FCEF32E745F2C3D5.

I was hoping for a fix and tried the above solution but that did not work for me. i know my IaC was working about 2~3 weeks ago which used the same roles and playbooks.

The failure returned (short version) was:
```
key_id: FCEF32E745F2C3D5                                                                                                                                                                     
msg: apt-key did not return an error, but failed to add the key (check that the id is correct and *not* a subkey)
```
I am using the wcm-io-devops/jenkins-pipeline-library which is using geerlingguy's jenkins playbook.

The full failure returned was:
```
TASK [geerlingguy.jenkins : Add Jenkins apt repository key.] ********************************************************************************************************************************
fatal: [jenkins-staging]: FAILED! => changed=true
after:
- 54422A4B98AB5139
- B6748A65281DDC4B
- A2F683C52980AECF
- AD18C79D920E471F
- 8D81803C0EBFCD88
- 7EA0A9C3F273FCD8
- 1655A0AB68576280
- 6C5CDECAAA01DA2C
- 5BA31D57EF5975CA
- 14EDB24CE3E1422E
- 73A4F27B8DD47936
- 0E98404D386FA1D9
- A48449044AAD5C5D
- 54404762BBB6E853
- 605C66F00D6C9793
- DC30D7C23CBBABEE
- 648ACFD622F3D138
- 4DFAB270CAA96DFA
- 112695A0E562B32A
- DCC9EFBF77E11517
- E0B11894F66AEC98
- 04EE7237B7D453EC
- EDA0D2388AE22BA9
- AA8E81B4331F7F50
- EF0F382A1A7B6500
- F9177B5265F56346
- 6F0F6BA0310BFCD4
- F9177B5265F56346
- 6F0F6BA0310BFCD4
before:
- 54422A4B98AB5139
- B6748A65281DDC4B
- A2F683C52980AECF
- AD18C79D920E471F
- 8D81803C0EBFCD88
- 7EA0A9C3F273FCD8
- 1655A0AB68576280
- 6C5CDECAAA01DA2C
- 5BA31D57EF5975CA
- 14EDB24CE3E1422E
- 73A4F27B8DD47936
- 0E98404D386FA1D9
- A48449044AAD5C5D
- 54404762BBB6E853
- 605C66F00D6C9793
- DC30D7C23CBBABEE
- 648ACFD622F3D138
- 4DFAB270CAA96DFA
- 112695A0E562B32A
- DCC9EFBF77E11517
- E0B11894F66AEC98
- 04EE7237B7D453EC
- EDA0D2388AE22BA9
- AA8E81B4331F7F50
- EF0F382A1A7B6500
- F9177B5265F56346
- 6F0F6BA0310BFCD4
- F9177B5265F56346
- 6F0F6BA0310BFCD4
fp: FCEF32E745F2C3D5
id: FCEF32E745F2C3D5
key_id: FCEF32E745F2C3D5                                                                                                                                                                     
msg: apt-key did not return an error, but failed to add the key (check that the id is correct and *not* a subkey)
short_id: 45F2C3D5
```
