### ISSUE TITLE
Allow installing a given jenkins version

### ISSUE THREAD

**Issue by hoxu** [geerlingguy/ansible-role-jenkins#38]
Greetings from downstream ([solita/ansible-role-solita.jenkins](https://github.com/solita/ansible-role-solita.jenkins))!

As part of the effort of making a Jenkins installation completely configurable and reproducible with Ansible, we are looking into allowing installation of a specific Jenkins version.

The most likely way to go is to use the packages on http://mirrors.jenkins-ci.org/ for specific versions.

This is a heads-up: are you interested in reviewing (and merging) such a feature into ansible-role-jenkins?

And do you have any thoughts / concerns at this point?

**Comment by geerlingguy** [comment]
@hoxu - Hi! I'd be interested if it's really simple (e.g. less than a task or two and no structural changes to the role) to support this feature—but this role uses the official Jenkins repos, and installs the latest version, which also allows easy updates going forward... I don't favor pinning to older versions if it can be helped.

**Comment by geerlingguy** [comment]
It looks like the best option is to do something like this: https://github.com/geerlingguy/ansible-role-jenkins/issues/47#issuecomment-212861640
