### ISSUE TITLE
Vars prefix

### ISSUE THREAD

**Issue by deimosfr** [geerlingguy/ansible-role-jenkins#4]
Hi,

I have a suggestion: it would be great to have prefix on your vars like this:

* jenkins_hostname

Thanks

**Comment by geerlingguy** [comment]
Quite true! I'll add this soon, and make sure it's in a new minor release, since the variable name could break some people's configurations.

**Comment by deimosfr** [comment]
Thanks :-)

**Comment by geerlingguy** [comment]
I've added this and incremented minor version to 1.2.0 since it will require people to update their vars. Should be a simple update.
