### ISSUE TITLE
configuring jobs

### ISSUE THREAD

**Issue by frob** [geerlingguy/ansible-role-jenkins#44]
how would one go about configuring jobs. Say we have all the xml configuration from a previously installed jenkis.

**Comment by geerlingguy** [comment]
I'd typically recommend the [Job Import Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Job+Import+Plugin); Jenkins 2.0, however, includes a new feature that allows you to define Jenkins jobs (somewhat at least) via a [Jenkinsfile](https://wiki.jenkins-ci.org/display/JENKINS/2.0+Pipeline+as+Code).

For now, I usually have a job exported to XML and then import it after Jenkins is set up; see, for example, https://github.com/geerlingguy/drupalci-sonar-jenkins/blob/master/provisioning/tasks/jenkins-setup.yml#L31-L42

**Comment by frob** [comment]
Wow, that is cool. i hadn't known about either of those. I will have to read up on the Jenkinsfile stuff.

**Comment by shurick81** [comment]
Is it possible to propagate jobs in J2 using Jenkinsfile via this ansible role?
