### ISSUE TITLE
Empty jenkins_url_prefix breaking jenkins updates?

### ISSUE THREAD

**Issue by ricardclau** [geerlingguy/ansible-role-jenkins#52]
Hi

I am facing a weird issue when running updates on an existing Jenkins 2.x server
The update process is complaining about the last line in /etc/default/jenkins because $PREFIX is empty (which is the role's default value)

```
JENKINS_ARGS+=" --prefix="
```

Is there any workaround for that?

**Comment by gaieges** [comment]
This was fixed [here](https://github.com/geerlingguy/ansible-role-jenkins/pull/39), but it looks like it regressed.

I don't think it's because of the prefix being empty, it's because bash doesnt like += (or at least that was my problem).  Try changing it to 

```
JENKINS_ARGS="$JENKINS_ARGS --prefix="

**Comment by ricardclau** [comment]
Ping @geerlingguy do you want me to send a Pull request like the one @gaieges sent a while ago? Don't understand why it regressed :(

**Comment by geerlingguy** [comment]
Merged in PR; thanks!
