### ISSUE TITLE
Provide option to set runSetupWizard=false in JENKINS_JAVA_OPTIONS

### ISSUE THREAD

**Issue by blaffoy** [geerlingguy/ansible-role-jenkins#66]
Without this option `-Djenkins.install.runSetupWizard=false`, on a new install of Jenkins 2.0 it will require some manual intervention in the GUI in order to complete deployment so that the proper Jenkins homepage will be displayed.

I use this role to test deployments of Jenkins along for new plugin development, changes to Jenkins Job Builder config, and groovy scripts for interacting with internal Jenkins settings. The Setup Wizard interferes with proper testing of this.

I propose adding this option to JENKINS_JAVA_OPTIONS in the service config file (or adding an ansible var that allows arbitrary strings to be added to this). This file is at `/etc/sysconfig/jenkins` in a RedHat install, but I don't know how that will vary by OS/distribution.

**Comment by geerlingguy** [comment]
Looks like a good idea to me. I dislike setup wizards regardless of testing and such—that's the reason I'm using Ansible :) 

I left a comment on the PR—I'd be okay with explicitly setting this to `false` as a default.

**Comment by geerlingguy** [comment]
PR has been merged—thanks!
