### ISSUE TITLE
CHANGELOG file?

### ISSUE THREAD

**Issue by tknerr** [geerlingguy/ansible-role-jenkins#74]
I was just looking for the changes that have been introduced in 2.3.0. Was not too hard to look at the diffs, but a CHANGELOG.md file would have been nice, actually.

Btw: props for making all the tasks idempotent, I really like to see that on the 2nd run:
```
PLAY RECAP *********************************************************************
default                    : ok=25   changed=0    unreachable=0    failed=0
```

**Comment by tknerr** [comment]
P.S: this is the link to the compare view I used:
https://github.com/geerlingguy/ansible-role-jenkins/compare/2.2.0...2.3.0

**Comment by geerlingguy** [comment]
@tknerr - I also like a well-curated CHANGELOG for larger projects, but for all these roles, it would be too much a burden for me to maintain, and I try to ensure the git history (and release frequency) is clean enough that it can serve as a 'poor-mans-changelog'.

**Comment by tknerr** [comment]
was just wondering, thanks for the clarification!

**Comment by geerlingguy** [comment]
No problem!
