### ISSUE TITLE
Debian based os fail to install plugins when using Jenkins v2+

### ISSUE THREAD

**Issue by johnpneumann** [geerlingguy/ansible-role-jenkins#78]
Based on the conversation in #70, there are issues with the way that the cli interacts on Debian based OS'. The current workaround is to add in:

```
jenkins_init_changes:
  - option: "JAVA_ARGS"
    value: "-Dhudson.diyChunking=false"
```

to your playbook vars, which overrides any of the other defaults that do exist. It also requires the user to know that they need to add that in, since it's not readily apparent why it's not working.

Because this appears to be an upstream issue, having to get around this in any sane way can be hackish because it requires changes to the ansible role that have little to do with Jenkins in general. Providing a good user experience, however, may be appropriate since there appears to be a workaround in place.

Options at hand are to split out settings and have them separate for rpm/deb based distros and merge the defaults, with user configs. Alternatively, there's the option to have an option, called `merge_jenkins_defaults` which would then do that merge.

**Comment by johnpneumann** [comment]
@geerlingguy @leifmadsen - Let me know if I've left anything out and how I can assist.

**Comment by geerlingguy** [comment]
Thanks!

**Comment by mnothic** [comment]
This doesn't work the plugins installation and the authentication with admin user in ubuntu 16.04 some solution is coming or this role is abandoned?

**Comment by geerlingguy** [comment]
@mnothic - This role is currently in maintenance mode; I have not had to build new Jenkins infrastructure in 2017 yet, so it hasn't been on the front burner. Note that I still check into any PR that comes my way, and as with any of my projects, if there's a simple, well-documented change that follows the current style/formatting, and fixes an existing bug (and still allows all tests to pass), then I will likely consider merging that PR.

**Comment by geerlingguy** [comment]
Also, a workaround could be installing/managing the plugins downstream, in your playbook; or via a separate role. My intention is to allow plugin management in this role, but it could be a while before I get around to testing things with the latest versions of Jenkins—a lot changed with 2.0, and a lot of little things still keep changing in minor versions!
