### ISSUE TITLE
I can not enter to jenkins with user admin and pass admin

### ISSUE THREAD

**Issue by ronsonmaria** [geerlingguy/ansible-role-jenkins#79]
Hello,

I put in my config.yml this configuration:
# jenkins configuration.

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_hostname: localhost
jenkins_repo_url: deb http://pkg.jenkins-ci.org/debian-stable binary/
jenkins_repo_key_url: http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_plugins:
- git
- sonar
- ssh
  jenkins_url_prefix: ""
  #ssh_home: "{{ drupal_core_path }}"
  jenkins_admin_username: admin
  jenkins_admin_password: admin

But when open the page in browser, I have used admin admin and recive this message:

"Error de autenticación"

I have:

 Jenkins ver. 2.7.2 in the role:

Requirements: - src: geerlingguy.jenkins

Playbook:  - { role: geerlingguy.jenkins, when: '"jenkins" in installed_extras' }

Windows 10 + cygwin 32 bits

Thanks

**Comment by Grobix** [comment]
Hi there,

we got the same problem. After some research we recognized that the groovy script which creates a defined user on jenkins startup will be triggered but the condition `if (!instance.isUseSecurity()) {` will prevent the following code block to be executed. We removed the negation and rerun the playbook and all works fine.

In a second step we installed a jenkins directly from the repository. In this case the paramater `useSecurity` was allready true. 

Does anyone know what is the exact reason for the negation?

Kind regards 

Robin

**Comment by juju4** [comment]
Same problem here. removed the condition and works again.

**Comment by tknerr** [comment]
Same here, still investigating...

**Comment by slapula** [comment]
I agree with @Grobix that is a weird negation.  I'm not sure I understand why it's there.  Removing it did solve this problem for me.  I'm willing to submit a PR if this is a typo.

**Comment by noidi** [comment]
Are you by any chance applying this role over an existing Jenkins installation? If that's the case, the existing security configuration will not be touched (see my comment in #94).

You can either add the admin user manually or completely wipe out your existing Jenkins installation (uninstall the package and remove `/var/lib/jenkins`) and perform a clean installation.

**Comment by slapula** [comment]
I know that the problem I am having is with the the first run.  `admin/admin` should work once the role has been applied the first time but it's not.  What I did was remove the negation, spin up a fresh VM, then reapply the role. It works after that.   Maybe the security setting is not being set correctly on that initial run so that when it reaches user creation it fails to meet the `if` condition and skips it.

**Comment by slapula** [comment]
Correct me if Im wrong but it appears `UseSecurity` is set to true by default now after a fresh Jenkins install.  That's why the `if` condition is failing and not creating the admin user.

**Comment by reinholdB** [comment]
I'm running into the same issue on a vagrant box ubuntu/xenial64.

**Comment by lioramilbaum** [comment]
me as well on ec2 ubuntu/xenial64 instance. What is puzzling is that on some runs the admin user created on others it doesn't. Same code, different behavior.

**Comment by jmalacho** [comment]
I changed the template to this:
```
#!groovy
import hudson.security.*
import jenkins.model.*

def instance = Jenkins.getInstance()
def hudsonRealm = new HudsonPrivateSecurityRealm(false)
def users = hudsonRealm.getAllUsers()
users_s = users.collect { it.toString() }
if ("{{ jenkins_admin_username }}" in users_s) {
    println "Admin user already exists"
} else {
    println "--> creating local admin user"

    hudsonRealm.createAccount('{{ jenkins_admin_username }}', '{{ jenkins_admin_password }}')
    instance.setSecurityRealm(hudsonRealm)

    def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
    instance.setAuthorizationStrategy(strategy)
    instance.save()
}
```

As you can see, I'm conditioning on the existence of the first user.  As opposed to if security is enabled at all.

**Comment by slapula** [comment]
@jmalacho dude thank you!

**Comment by eigenhombre** [comment]
@jmalacho thanks!  This fixed the issue for me as well.  (I guess that until this is fixed in `ansible-galaxy`, most users are in for a pretty bad experience.)

**Comment by cristafortuno** [comment]
@jmalacho,

Hello. Just want to ask if for example, I have set the following under defaults/main.yml and using your code in basic-security.groovy

jenkins_admin_username: admin
jenkins_admin_password: admin

if I first access Jenkins in browser, am I supposed to be able to login as <admin/admin> or will it still be <admin/password set in /var/lib/jenkins/secrets/initialAdminPassword>?

My understanding is that <admin/admin> should be working when I first accessed Jenkins in browser, but, it was the <admin/password set in /var/lib/jenkins/secrets/initialAdminPassword> credentials that it accepted.

Thanks.

**Comment by cristafortuno** [comment]
@jmalacho, Please ignore above inquiry. It is now okay. :) Thanks!

**Comment by geerlingguy** [comment]
Testing this fix now.

**Comment by priyankasupi** [comment]
i couldnot login to my jenkins with admin user login

**Comment by okosodovictor** [comment]
I can't login to Jenkins, I have spent several hours on this using admin user login and i cant found the password folder

**Comment by sreeniwas** [comment]
Hi all
I have an issue which is frequently am getting in my jenkins server.
After creating some users , i was trying to get assign reole from manage jenkins.
Once I select the Role-based strategy in "Configure global security" immediately am getting error so that could not login in to my server eventhough i have correct username and password.
I am getting this error " HTTP ERROR 404

Problem accessing /securityRealm/. Reason: " frequently.
Can anybody please help me.
_
