### ISSUE TITLE
Problems when I install jenkins plugins

### ISSUE THREAD

**Issue by ronsonmaria** [geerlingguy/ansible-role-jenkins#80]
**Hello,

I have installed jenkins plugin:**

My jenkins configuration in config.yml
# jenkins configuration.

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_hostname: localhost
jenkins_repo_url: deb http://pkg.jenkins-ci.org/debian-stable binary/
jenkins_repo_key_url: http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_plugins:
- git
- sonar
- ssh
  jenkins_url_prefix: ""
  jenkins_admin_username: admin
  jenkins_admin_password: admin

**And the vagrant up said me:**

TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ***********
failed: [drupaltest](item=git) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://localhost:8080/", "install-plugin", "git", "--username", "admin", "--password", "admin"], "delta": "0:00:00.133402", "end": "2016-08-19 08:51:39.478404", "failed": true, "item": "git", "rc": 255, "start": "2016-08-19 08:51:39.345002", "stderr": "java.io.IOException: No X-Jenkins-CLI2-Port among [X-Jenkins, X-Required-Permission, null, X-You-Are-In-Group, Date, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Jenkins-Session, Set-Cookie, Content-Type, Server, X-Content-Type-Options]\n\tat hudson.cli.CLI.getCliTcpPort(CLI.java:284)\n\tat hudson.cli.CLI.<init>(CLI.java:128)\n\tat hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)\n\tat hudson.cli.CLI._main(CLI.java:473)\n\tat hudson.cli.CLI.main(CLI.java:384)\n\tSuppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/cli\n\t\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)\n\t\tat hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)\n\t\tat hudson.cli.CLI.connectViaHttp(CLI.java:152)\n\t\tat hudson.cli.CLI.<init>(CLI.java:132)\n\t\t... 3 more", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [drupaltest](item=sonar) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://localhost:8080/", "install-plugin", "sonar", "--username", "admin", "--password", "admin"], "delta": "0:00:00.125593", "end": "2016-08-19 08:51:39.799369", "failed": true, "item": "sonar", "rc": 255, "start": "2016-08-19 08:51:39.673776", "stderr": "java.io.IOException: No X-Jenkins-CLI2-Port among [X-Jenkins, X-Required-Permission, null, X-You-Are-In-Group, Date, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Jenkins-Session, Set-Cookie, Content-Type, Server, X-Content-Type-Options]\n\tat hudson.cli.CLI.getCliTcpPort(CLI.java:284)\n\tat hudson.cli.CLI.<init>(CLI.java:128)\n\tat hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)\n\tat hudson.cli.CLI._main(CLI.java:473)\n\tat hudson.cli.CLI.main(CLI.java:384)\n\tSuppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/cli\n\t\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)\n\t\tat hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)\n\t\tat hudson.cli.CLI.connectViaHttp(CLI.java:152)\n\t\tat hudson.cli.CLI.<init>(CLI.java:132)\n\t\t... 3 more", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [drupaltest](item=ssh) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://localhost:8080/", "install-plugin", "ssh", "--username", "admin", "--password", "admin"], "delta": "0:00:00.135267", "end": "2016-08-19 08:51:40.111703", "failed": true, "item": "ssh", "rc": 255, "start": "2016-08-19 08:51:39.976436", "stderr": "java.io.IOException: No X-Jenkins-CLI2-Port among [X-Jenkins, X-Required-Permission, null, X-You-Are-In-Group, Date, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Jenkins-Session, Set-Cookie, Content-Type, Server, X-Content-Type-Options]\n\tat hudson.cli.CLI.getCliTcpPort(CLI.java:284)\n\tat hudson.cli.CLI.<init>(CLI.java:128)\n\tat hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)\n\tat hudson.cli.CLI._main(CLI.java:473)\n\tat hudson.cli.CLI.main(CLI.java:384)\n\tSuppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/cli\n\t\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)\n\t\tat hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)\n\t\tat hudson.cli.CLI.connectViaHttp(CLI.java:152)\n\t\tat hudson.cli.CLI.<init>(CLI.java:132)\n\t\t... 3 more", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************

I have vagrant 1.8.5 in windows 10 :-)

**Comment by alexk-motu** [comment]
Yeah, this is actually a major issue with this playbook now. It tries to use the `--username` and `--password` flags for jenkins cli which have been deprecated for some time. I'm going to spend some time working on this today and hope to submit a pull request that uses key files instead of username/password auth.

**Comment by AndreasEK** [comment]
For me, it helped to just remove the parameters --username and --password:

In plugins.yml:
```
- name: Install Jenkins plugins using password.
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
    install-plugin {{ item }}
    creates="{{ jenkins_home }}/plugins/{{ item }}.jpi"
  with_items: "{{ jenkins_plugins }}"
  when: jenkins_admin_password != ""
  notify: restart jenkins
```

**Comment by AndreasEK** [comment]
See https://github.com/scrum-for-developers/scrum-for-developers-infra/issues/6 for details.

**Comment by olo-dw** [comment]
Since 4b493a4b57b15e408f24a31dea73db241003460c the install Jenkins plugins installation has changed in order to use the `jenkins_plugin` ansible module instead of `jenkins-cli.jar`.

In my opinion, this issue around jenkins-cli can be closed.

**Comment by geerlingguy** [comment]
Good catch, yes!
