### ISSUE TITLE
Scope of this role regarding plugins

### ISSUE THREAD

**Issue by thokari** [geerlingguy/ansible-role-jenkins#85]
Hi, 
I am currently enjoying your jenkins role, and was wondering whether you would regard to provide basic configurations for plugins in scope for this role?

Consider this example:

```
jenkins_plugins:
  - { id: ssh-credentials }
  - { id: credentials, configSrc: files/credentials.xml, configDest: credentials.xml }
  - { id: email-ext, configTemplate: templates/hudson.plugins.emailext.ExtendedEmailPublisher.xml.jj2, configDest: hudson.plugins.emailext.ExtendedEmailPublisher.xml }
```

The point is the initial installation of the plugins is not the problem compared to configuring them.

**Comment by lioramilbaum** [comment]
+1

**Comment by thokari** [comment]
Of course the actual files would need to be supplied by the end user, but it would really help if there already was a mechanism to include and template them.
There also is the https://wiki.jenkins-ci.org/display/JENKINS/Job+DSL+Plugin, which we are using  through https://github.com/ghale/gradle-jenkins-plugin/wiki, in order to be able to run it externally, during installation time.
Without elaborating too much about our concrete use case, I don't think that either way of configuring Jenkins will solve every problem, so realistically a combination of both ways will happen, as it is right now in our case. And the basic plugin configuration I see more on the Ansible side...

**Comment by thokari** [comment]
Also, several configuration files require the version number of a plugin, which Ansible could know about while installing it.

**Comment by thokari** [comment]
I have decided now to solve the problem of initally configuring Jenkins according to this:
https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Jenkins+upon+start+up

So the complete process looks like this:

1. Run playbook which includes this role
2. The playbook also templates/copies said init.groovy.d files, to set up Jenkins main configuration and plugins
3. Run Job DSL to create the actual jobs

However. the goal is to have more or less every variable defined via Ansible.
So feel free to close this issue as I will not be requesting this feature.

By the way, I also bought your book, it is nice ;)

**Comment by webratz** [comment]
can you share your scripts so this could be used by others?

**Comment by jainendrakumar10** [comment]
Yes, kindly share the script to configure the plugins and how you integrated the script into the role.

**Comment by shanedroid** [comment]
Just sharing what ended up working for me to be able to handle plugins for Jenkins using a wrapper role:

https://gist.github.com/shanedroid/b9ffd39417c0c799481fb275392901bb
