### ISSUE TITLE
Wait for Jenkins to start up before proceeding - fails on a dry run

### ISSUE THREAD

**Issue by canha** [geerlingguy/ansible-role-jenkins#96]
Hi @geerlingguy,
## Context

The step "_Wait for Jenkins to start up before proceeding._" fails when you invoke this role with a playbook in _--check_ mode (dry run). This doesn't happen on the normal run.
## Expected Behavior

Continue the checks after verifying that the Jenkins instance is up.
## Actual Behavior

Ansible fails with:

> FAILED! => {"failed": true, "msg": "The conditional check '(result.stdout.find(\"403 Forbidden\") != -1) or (result.stdout.find(\"200 OK\") != -1) and (result.stdout.find(\"Please wait while\") == -1)' failed. The error was: error while evaluating conditional ((result.stdout.find(\"403 Forbidden\") != -1) or (result.stdout.find(\"200 OK\") != -1) and (result.stdout.find(\"Please wait while\") == -1)): 'dict object' has no attribute 'stdout'"}

## Steps to Reproduce
1. Include this role on a playbook
2. Specify jenkins_version as 2.19.1
3. Specify jenkins_pkg_url as http://pkg.jenkins-ci.org/debian-stable/binary/
4. Set a jenkins_admin_username and a jenkins_admin_password together with the normal suggested plugins on jenkins_plugins
5. Do a normal run, let it install
6. Now do a dry run with --check
## Environment
- Version used: Ansible 2.1.2.0
- OS where Ansible runs from: macOS 10.12.1
- Target OS: [Debian 8 (Vagrant)](https://atlas.hashicorp.com/debian/boxes/contrib-jessie64)

**Comment by choglundsp** [comment]
I submitted a PR(https://github.com/geerlingguy/ansible-role-jenkins/pull/102) for this issue.
